import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import { PracticeStore, hashCode } from '../../src/storage/practice-store';
import { InterviewService } from '../../src/interview/service';
import { buildPool, selectCandidates, validateRules } from '../../src/interview/sampling';
import { normalizeCompany, parseCompanyFile } from '../../src/interview/company';
import { defaultInterviewRules, type InterviewRules, type CompanyDataset } from '../../src/shared/interview';
import type { ProblemContent } from '../../src/shared/library';
const problem=(id='local:one',difficulty='中等'):ProblemContent=>({id,title:`题目 ${id}`,difficulty,tags:['数组','哈希表'],source:'local',description:'返回整数数组元素和。',descriptionFormat:'plain',constraints:[],mode:'function',adapter:{method:'sum',params:[{array:'int'}],returns:'int'},cases:[{args:[[1,2]],expected:3}],starter:{python:'class Solution:\n    def sum(self, nums):\n        return 0',java:'class Solution { public int sum(int[] nums) { return 0; } }'}});
const rules=(patch:Partial<InterviewRules>={}):InterviewRules=>({...defaultInterviewRules,counts:{...defaultInterviewRules.counts},excludeRecentDays:0,seed:'stable-seed',...patch});
function fixture(t:{after:(fn:()=>void)=>void}){
  const dir=mkdtempSync(join(tmpdir(),'Algo P4 面试 ')),path=join(dir,'practice.sqlite');let store=new PracticeStore(path),wall=Date.now(),mono=0;
  store.upsertProblem(problem());store.upsertProblem(problem('local:two'));store.upsertProblem(problem('local:easy','简单'));
  let service=new InterviewService({store:()=>store,clock:{wall:()=>wall,monotonic:()=>mono}});
  t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});
  return {dir,path,get store(){return store;},get service(){return service;},advance:(ms:number)=>{wall+=ms;mono+=ms;},wallJump:(ms:number)=>{wall+=ms;},restart:()=>{store.close();store=new PracticeStore(path);service=new InterviewService({store:()=>store,clock:{wall:()=>wall,monotonic:()=>mono}});},start:async(patch:Partial<InterviewRules>={})=>{const p=service.preview(rules(patch));return service.start(p.id,'start-'+Math.random());}};
}

test('E14: same canonical pool and seed reproduce stratified selection independent of input order',t=>{const f=fixture(t),input=rules({counts:{easy:1,medium:2,hard:0}}),a=buildPool(f.store.listProblems(),[],input,null),b=buildPool(f.store.listProblems().reverse(),[],input,null,a.evaluatedAt);assert.deepEqual(a,b);assert.equal(new Set(a.selectedIds).size,3);assert.deepEqual(selectCandidates(a.candidates,input),a.selectedIds);});
test('E14: candidate shortage and unsupported language never relax silently',t=>{const f=fixture(t);f.store.upsertProblem({...problem('local:missing'),starter:{},cases:[]});const p=f.service.preview(rules({counts:{easy:0,medium:3,hard:0}})).pool;assert.equal(p.selectedIds.length,0);assert.match(p.shortages.join(),/缺 1/);assert.ok(p.exclusions.find(e=>e.problemId==='local:missing'));});
test('E14: recent attempts exclude across languages and tags filter accurately',t=>{const f=fixture(t),p=f.store.getProblem('local:one')!;f.store.startAttempt({problemId:p.id,language:'java',problemVersion:p.version});const pool=f.service.preview(rules({excludeRecentDays:14,tags:['数组']})).pool;assert.deepEqual(pool.candidates.map(c=>c.problem.id),['local:two']);assert.equal(f.service.preview(rules({tags:['不存在']})).pool.selectedIds.length,0);});
test('configuration rejects malformed counts, empty seeds, unlimited time and missing dataset',()=>{for(const patch of [{durationMinutes:0},{durationMinutes:NaN},{seed:''},{counts:{easy:0,medium:0,hard:0}},{counts:{easy:11,medium:0,hard:0}},{excludeRecentDays:-1},{sampling:'frequency'},{company:'a'}] as Partial<InterviewRules>[])assert.throws(()=>validateRules(rules(patch)));});
test('company CSV preserves original names, normalizes NFKC/case/space and keeps unknown dates',()=>{const text='company,problemId\n" ＡＣＭＥ  Inc ",local:one\n" ＡＣＭＥ  Inc ",local:one';const p=parseCompanyFile({kind:'csv',name:'公司.csv',text},new Set(['local:one']));assert.equal(p.duplicates,1);assert.equal(p.dataset.entries[0].company,'ＡＣＭＥ  Inc');assert.equal(p.dataset.entries[0].normalizedCompany,'acme inc');assert.equal(p.dataset.entries[0].dataDate,null);assert.equal(p.dataset.entries[0].frequency,null);assert.equal(p.missingProblemIds.length,0);assert.equal(p.dataset.fileHash.length,64);assert.equal(normalizeCompany('ＡＢＣ'),'abc');});
test('company invalid URLs, impossible dates, negative/nonfinite frequencies and conflicting identity block commit',t=>{const f=fixture(t);for(const row of [{company:'a',url:'file:///tmp/no'},{company:'a',url:'https://leetcode.cn/problems/two-sum/',problemId:'local:one'},{company:'a',problemId:'x',dataDate:'2026-02-30'},{company:'a',problemId:'x',frequency:-1},{company:'a',problemId:'x',frequency:'Infinity'}]){const p=f.service.previewCompany({kind:'json',name:'bad',text:JSON.stringify([row])});assert.equal(p.preview.errors.length,1);assert.throws(()=>f.service.commitCompany(p.id));}});
test('E14: duplicate company associations never duplicate questions or sum frequency',t=>{const f=fixture(t);const p=f.service.previewCompany({kind:'json',name:'companies.json',text:JSON.stringify([{company:'Acme',problemId:'local:one',window:'2026',frequency:2,frequencyMeaning:'mentions'},{company:'ACME',problemId:'local:one',window:'2026',frequency:2,frequencyMeaning:'mentions'},{company:'Acme',problemId:'local:two',window:'2026',frequency:1,frequencyMeaning:'mentions'}])});const d=f.service.commitCompany(p.id),pool=f.service.preview(rules({company:'Acme',datasetId:d.id,sampling:'frequency',counts:{easy:0,medium:2,hard:0}})).pool;assert.equal(pool.candidates.length,2);assert.equal(pool.candidates.find(c=>c.problem.id==='local:one')?.weight,2);assert.equal(new Set(pool.selectedIds).size,2);});
test('unknown or mixed frequency semantics/windows require explicit uniform selection',t=>{const f=fixture(t);for(const entries of [[{company:'a',problemId:'local:one',frequency:1}],[{company:'a',problemId:'local:one',frequency:1,window:'x',frequencyMeaning:'mentions'},{company:'a',problemId:'local:two',frequency:1,window:'y',frequencyMeaning:'mentions'}],[{company:'a',problemId:'local:one',frequency:1,window:'x',frequencyMeaning:'mentions'},{company:'a',problemId:'local:one',frequency:2,window:'x',frequencyMeaning:'mentions'}]]){const p=f.service.previewCompany({kind:'json',name:'data',text:JSON.stringify(entries)}),d=f.service.commitCompany(p.id);const weighted=f.service.preview(rules({company:'a',datasetId:d.id,sampling:'frequency'})).pool;assert.ok(weighted.shortages.length);assert.equal(weighted.selectedIds.length,0);assert.equal(f.service.preview(rules({company:'a',datasetId:d.id})).pool.selectedIds.length,1);}});
test('frequency zero excluded and tiny/large finite weights remain deterministically ordered',t=>{const f=fixture(t),p=f.service.previewCompany({kind:'json',name:'weights',text:JSON.stringify([{company:'a',problemId:'local:one',frequency:0,window:'x',frequencyMeaning:'mentions'},{company:'a',problemId:'local:two',frequency:2,window:'x',frequencyMeaning:'mentions'}])}),d=f.service.commitCompany(p.id);assert.deepEqual(f.service.preview(rules({company:'a',datasetId:d.id,sampling:'frequency'})).pool.selectedIds,['local:two']);});
test('E15: dedicated scopes never expose or replace existing practice solutions',async t=>{const f=fixture(t);for(const p of f.store.listProblems())f.store.saveDraft({problemId:p.id,language:'python',code:'SECRET_SOLUTION'});const v=await f.start();const item=v.session.items[0];assert.ok(!JSON.stringify(v).includes('SECRET_SOLUTION'));assert.ok(!JSON.stringify(v).includes('哈希表'));assert.equal(v.session.pool.candidates.length,0);assert.equal(f.store.getDraft(item.problem.id,'python')?.code,'SECRET_SOLUTION');assert.notEqual(item.scopeId,'practice');});
test('E15: strict mode blocks direct legacy IPC, old pages, notes, exports, source and all AI help',async t=>{const f=fixture(t);const v=await f.start();for(const channel of ['library:list','practice:workspace','draft:load','draft:save','runner:run','archive:get','archive:list','archive:restore','submission:history','submission:detail','submission:save-remark','note:list','note:get','note:versions','note:export','attachment:get','attachment:read','attachment:export','ai:ask','ai:requests','ai:preview-patch','ai:apply-patch','app:open-web-link','app:copy-code','source:login','backup:restore','company:preview'])assert.throws(()=>f.service.assertChannel(channel,[]),/严格/);for(const channel of ['interview:get','interview:save','interview:finish','interview:coach','interview:run'])assert.doesNotThrow(()=>f.service.assertChannel(channel,[v.session.id]));assert.throws(()=>f.service.assertChannel('interview:get',['old']),/当前面试/);});
test('E15: starting cancels/isolate outstanding AI and rejects old generation response',async t=>{const f=fixture(t);let release!:()=>void;const waiting=new Promise<void>(resolve=>{release=resolve;});let cancelled=false;const svc=new InterviewService({store:()=>f.store,beforeStart:async()=>{cancelled=true;await waiting;}});const before=svc.epoch,p=svc.preview(rules()),pending=svc.start(p.id,'request');assert.equal(cancelled,true);assert.throws(()=>svc.assertChannel('ai:ask'),/正在准备/);release();await pending;assert.throws(()=>svc.assertResponse('archive:get',[],before),/严格|隔离/);});
test('E15: coached transition is permanent, recorded and AI trusted context derives from session',async t=>{const f=fixture(t),v=await f.start();const before=f.service.assertAiContext({attemptId:'old',mode:'practice',isActive:false} as never);assert.equal(before.mode,'strict');assert.equal(before.isActive,true);const changed=f.service.coach(v.session.id);assert.equal(changed.session.mode,'coached');assert.equal(changed.session.initialMode,'strict');assert.equal(changed.session.modeChanges.length,1);assert.equal(f.service.coach(v.session.id).session.modeChanges.length,1);const context=f.service.assertAiContext({attemptId:changed.items[0].attempt.id,mode:'strict',isActive:true} as never);assert.equal(context.mode,'coached');f.service.recordHelp('note:get','note1');assert.equal(f.service.view(v.session.id).session.help.length,1);assert.doesNotThrow(()=>f.service.assertChannel('note:list'));assert.throws(()=>f.service.assertChannel('draft:save',[v.items[0].item.problem.id,'python','code',v.items[0].item.scopeId]),/工作台/);});
test('E19: deadline freezes latest acknowledged save, late code becomes separate recap',async t=>{const f=fixture(t),v=await f.start({durationMinutes:1}),item=v.session.items[0];f.advance(59000);assert.equal(f.service.save(v.session.id,item.problem.id,'before','思路').counted,true);f.advance(1000);const late=f.service.save(v.session.id,item.problem.id,'after','迟到');assert.equal(late.counted,false);assert.equal(late.recap?.code,'after');const finished=f.service.view(v.session.id);assert.equal(finished.session.endReason,'deadline');assert.equal(finished.session.items[0].final?.code,'before');assert.equal(finished.items[0].attempt.finalCode,'before');assert.equal(finished.items[0].attempt.isActive,false);assert.throws(()=>f.service.runTarget(v.session.id,item.problem.id,false),/补测/);});
test('E19: request arriving before deadline but actual code commit finishing late is excluded',async t=>{const f=fixture(t),v=await f.start({durationMinutes:1}),item=v.session.items[0];f.service.save(v.session.id,item.problem.id,'acknowledged','');f.advance(59999);const save=f.store.saveDraft.bind(f.store);let delayed=false;f.store.saveDraft=input=>{const result=save(input);if(!delayed){delayed=true;f.advance(2);}return result;};const result=f.service.save(v.session.id,item.problem.id,'late commit','');assert.equal(result.counted,false);assert.equal(f.service.view(v.session.id).session.items[0].final?.code,'acknowledged');assert.equal(result.recap?.code,'late commit');});
test('E19: bookkeeping finishing after deadline cannot acknowledge a late revision',async t=>{const f=fixture(t),v=await f.start({durationMinutes:1}),item=v.session.items[0];f.service.save(v.session.id,item.problem.id,'acknowledged','');f.advance(59000);const update=f.store.updateInterview.bind(f.store);let delayed=false;f.store.updateInterview=session=>{update(session);if(!delayed&&session.items[0].accepted.code==='late bookkeeping'){delayed=true;f.advance(1001);}};const result=f.service.save(v.session.id,item.problem.id,'late bookkeeping','');assert.equal(result.counted,false);assert.equal(f.service.view(v.session.id).session.items[0].final?.code,'acknowledged');});
test('E19: manual finish while run queued is idempotent and late result never replaces final code',async t=>{const f=fixture(t),v=await f.start(),item=v.session.items[0];f.service.save(v.session.id,item.problem.id,'old code','');f.store.saveRun({id:'late-run',attemptId:item.attemptId,code:'old code',testSuiteVersion:'t',adapterVersion:'a',runtimeVersion:'r'});f.service.save(v.session.id,item.problem.id,'final code','');const end=f.service.finish(v.session.id);f.store.finishRun('late-run',{status:'wrong_answer',result:{status:'wrong_answer',caseResults:[]}});assert.deepEqual(f.service.finish(v.session.id).session,end.session);assert.equal(f.store.getAttempt(item.attemptId)?.finalCode,'final code');assert.equal(f.store.getAttempt(item.attemptId)?.lastRunMatchesFinal,false);assert.equal(f.service.view(v.session.id).items[0].runs[0].code,'old code');});
test('E19: only frozen code can receive a supplement Run after session ends',async t=>{const f=fixture(t),v=await f.start(),item=v.session.items[0];f.service.save(v.session.id,item.problem.id,'final','');f.service.finish(v.session.id);const base={attemptId:item.attemptId,testSuiteVersion:'t',adapterVersion:'a',runtimeVersion:'r'};assert.throws(()=>f.store.saveRun({...base,code:'different'}));assert.doesNotThrow(()=>f.store.saveRun({...base,code:'final'}));assert.equal(f.service.runTarget(v.session.id,item.problem.id,true).code,'final');});
test('E19: application restart preserves the original deadline and acknowledged answer',async t=>{const f=fixture(t),v=await f.start({durationMinutes:1}),item=v.session.items[0];f.service.save(v.session.id,item.problem.id,'saved before restart','');f.advance(40000);f.service.tick();f.restart();assert.equal(f.service.view(v.session.id).session.deadlineAt,v.session.deadlineAt);f.advance(20000);assert.equal(f.service.view(v.session.id).session.items[0].final?.code,'saved before restart');});
test('E19: resume after sleep beyond deadline freezes without adding time',async t=>{const f=fixture(t),v=await f.start({durationMinutes:1});f.wallJump(120000);f.service.tick(true);const s=f.service.view(v.session.id).session;assert.equal(s.deadlineAt,v.session.deadlineAt);assert.equal(s.endReason,'deadline');assert.equal(s.clockAnomalies.length,0);});
test('E19: forward/backward clock changes mark anomaly and freeze instead of extending',async t=>{for(const delta of [-10000,10000]){const f=fixture(t),v=await f.start();f.wallJump(delta);f.service.tick();const s=f.service.view(v.session.id).session;assert.equal(s.endReason,'clock-anomaly');assert.equal(s.clockAnomalies.length,1);assert.equal(s.deadlineAt,v.session.deadlineAt);}});
test('E19: rollback clock across process restart is detected using persisted observation',async t=>{const f=fixture(t),v=await f.start();f.advance(10000);f.service.tick();f.wallJump(-15000);f.restart();assert.equal(f.service.view(v.session.id).session.endReason,'clock-anomaly');});
test('E20: source/dataset refresh cannot alter finished report and repeat review does not rate',async t=>{const f=fixture(t),preview=f.service.previewCompany({kind:'json',name:'original',text:JSON.stringify([{company:'a',problemId:'local:one'}])}),dataset=f.service.commitCompany(preview.id),v=await f.start({company:'a',datasetId:dataset.id});f.service.finish(v.session.id);const frozen=f.service.view(v.session.id).session;f.store.upsertProblem({...problem('local:one'),description:'refreshed statement'});f.service.commitCompany(f.service.previewCompany({kind:'json',name:'new',text:JSON.stringify([{company:'a',problemId:'local:two'}])}).id);assert.deepEqual(f.service.view(v.session.id).session,frozen);const a=f.service.addReview(v.session.id,'local:one'),b=f.service.addReview(v.session.id,'local:one');assert.equal(a.id,b.id);assert.equal(f.store.listReviewEvents(a.id).length,0);assert.equal(a.language,'python');});
test('interview request id and company file are idempotent, concurrent sessions rejected',async t=>{const f=fixture(t),p=f.service.preview(rules()),v=await f.service.start(p.id,'one');assert.equal((await f.service.start(p.id,'one')).session.id,v.session.id);await assert.rejects(f.service.start(p.id,'another'),/已有/);const f2=fixture(t),p2=f2.service.previewCompany({kind:'json',name:'a',text:'[{"company":"a","problemId":"local:one"}]'});assert.equal(f2.service.commitCompany(p2.id).id,f2.service.commitCompany(p2.id).id);assert.equal(f2.store.listCompanyDatasets().length,1);});
test('interview reports and attempts are immutable at SQL boundary and references protect deletion',async t=>{const f=fixture(t),v=await f.start();f.service.finish(v.session.id);const db=new DatabaseSync(f.path);try{assert.throws(()=>db.prepare("UPDATE interview_sessions SET data_json='{}' WHERE id=?").run(v.session.id),/immutable/);assert.throws(()=>db.prepare("UPDATE attempts SET final_code='tamper' WHERE id=?").run(v.session.items[0].attemptId),/immutable/);}finally{db.close();}assert.throws(()=>f.store.deleteEndedAttempt(v.session.items[0].attemptId));assert.ok(f.store.getAttempt(v.session.items[0].attemptId));});
test('consistent SQLite backup restores company datasets, active timer and frozen reports',async t=>{const f=fixture(t),company=f.service.previewCompany({kind:'json',name:'c',text:'[{"company":"a","problemId":"local:one"}]'});f.service.commitCompany(company.id);const v=await f.start(),item=v.session.items[0];f.service.save(v.session.id,item.problem.id,'restorable','');const path=join(f.dir,'backup.sqlite');await f.store.backupTo(path);const restored=new PracticeStore(path);try{assert.equal(restored.getActiveInterview()?.deadlineAt,v.session.deadlineAt);assert.equal(restored.getInterview(v.session.id)?.items[0].accepted.code,'restorable');assert.equal(restored.listCompanyDatasets().length,1);assert.equal(PracticeStore.inspectBackupSnapshot(path).schemaVersion,7);}finally{restored.close();}});
test('real v4 schema migrates only after unchanged backup; repeated startup is idempotent',t=>{const dir=mkdtempSync(join(tmpdir(),'Algo P4 migration ')),path=join(dir,'practice.sqlite');t.after(()=>rmSync(dir,{recursive:true,force:true}));const old=new DatabaseSync(path);old.exec(readFileSync(new URL('../storage/fixtures/p3-v4-schema.sql',import.meta.url),'utf8'));old.exec("INSERT INTO problems VALUES ('old'); INSERT INTO drafts VALUES ('old','python','practice','print(7)','hash',1,'2026-09-01T00:00:00Z')");old.close();const store=new PracticeStore(path);try{assert.ok(store.migrationBackupPath&&existsSync(store.migrationBackupPath));assert.equal(store.getDraft('old','python')?.code,'print(7)');assert.equal(PracticeStore.inspectBackupSnapshot(store.migrationBackupPath!).schemaVersion,4);assert.equal(store.getActiveInterview(),null);assert.equal(store.listCompanyDatasets().length,0);store.integrityCheck();}finally{store.close();}const repeat=new PracticeStore(path);try{assert.equal(repeat.migrationBackupPath,null);assert.equal(repeat.getDraft('old','python')?.code,'print(7)');}finally{repeat.close();}});
test('failed v4 migration retains original schema and recoverable backup',t=>{const dir=mkdtempSync(join(tmpdir(),'Algo P4 bad migration ')),path=join(dir,'practice.sqlite');t.after(()=>rmSync(dir,{recursive:true,force:true}));const old=new DatabaseSync(path);old.exec(readFileSync(new URL('../storage/fixtures/p3-v4-schema.sql',import.meta.url),'utf8'));old.exec('CREATE TABLE interview_sessions(unexpected TEXT);');old.close();assert.throws(()=>new PracticeStore(path),/Schema v7 migration failed/);const db=new DatabaseSync(path);try{assert.equal(db.prepare('PRAGMA user_version').get()?.user_version,4);assert.equal(db.prepare("SELECT COUNT(*) AS count FROM sqlite_schema WHERE name='company_datasets'").get()?.count,0);}finally{db.close();}});
test('company links create shared library placeholders, leaving prepared problem content intact',t=>{const f=fixture(t);const before=f.store.getProblem('local:one')!;const p=f.service.previewCompany({kind:'json',name:'links',text:'[{"company":"a","problemId":"local:one"},{"company":"a","url":"https://leetcode.cn/problems/two-sum/"}]'});const dataset=f.service.commitCompany(p.id);const unknown=dataset.entries.find(e=>e.url)!;assert.ok(f.store.getProblem(unknown.problemId));assert.equal(f.store.getProblem(unknown.problemId)?.content.sourceUrl,unknown.url);assert.equal(f.store.getProblem(unknown.problemId)?.content.starter.python,undefined);assert.deepEqual(f.store.getProblem('local:one'),before);assert.equal(f.service.preview(rules({company:'a',datasetId:dataset.id})).pool.selectedIds.length,1);});

test('coached AI persistence validates current session mode while preserving original strict attempt',async t=>{
  const f=fixture(t),view=await f.start(),item=view.session.items[0];f.service.coach(view.session.id);
  const {buildRequestSnapshot,requestHash}=await import('../../src/ai/index');
  const {config}=await import('../ai/helpers');
  const context=f.service.assertAiContext({attemptId:item.attemptId,problemId:item.problem.id,problemVersion:item.problem.version,language:'python',mode:'strict',isActive:true,draftScopeId:item.scopeId,draftRevision:item.accepted.revision,code:item.accepted.code,reasoning:'按元素累加',problem:{title:item.problem.content.title,description:item.problem.content.description,constraints:[]},run:null,notes:[],conversation:[]});
  const snapshot=buildRequestSnapshot({requestId:'coached-ai',attemptId:item.attemptId,kind:'hint',question:'输入是什么？'},context,config());
  assert.equal(f.store.beginAIRequest({id:'coached-ai',attemptId:item.attemptId,requestHash:requestHash(snapshot),snapshot}).snapshot.mode,'coached');
  assert.equal(f.store.getAttempt(item.attemptId)?.mode,'strict');
  const forged={...snapshot,mode:'practice' as const};assert.throws(()=>f.store.beginAIRequest({id:'forged-ai',attemptId:item.attemptId,requestHash:requestHash(forged),snapshot:forged}),/persisted attempt/);
});
test('post-deadline code and reasoning survive restart only as recap; final reasoning remains frozen',async t=>{
  const f=fixture(t),view=await f.start(),item=view.session.items[0];f.service.save(view.session.id,item.problem.id,'answer','exam reasoning');f.service.finish(view.session.id);
  f.service.save(view.session.id,item.problem.id,'recap answer','later reasoning');f.restart();const restored=f.service.view(view.session.id);
  assert.equal(restored.session.items[0].final?.reasoning,'exam reasoning');assert.equal(restored.items[0].recap?.code,'recap answer');assert.equal(restored.items[0].recapReasoning,'later reasoning');
});
