import test from 'node:test';
import assert from 'node:assert/strict';
import { setTimeout as delay } from 'node:timers/promises';
import { AiService, AiServiceError, buildRequestSnapshot, canonicalJson, requestHash, sha256 } from '../../src/ai/index.ts';
import type { AiServiceOptions } from '../../src/ai/service.ts';
import type { AiEvent, AiProviderConfig, AiRequestInput } from '../../src/shared/ai.ts';
import { answer, config, context, input, jsonCompletion, MemoryRepository, mockVault, sseCompletion } from './helpers.ts';

function setup(fetcher?: typeof fetch) { const repository = new MemoryRepository(), source = context(), events: AiEvent[] = []; let calls = 0; const options: AiServiceOptions = { repository, vault: mockVault(), resolveContext: (_input: AiRequestInput) => source, resolveProvider: () => config() as AiProviderConfig | null, onEvent: (event: AiEvent) => { events.push(event); }, fetchImpl: fetcher ?? (async (_url, init) => { calls++; const messages = JSON.parse(String(init?.body)).messages; const sent = JSON.parse(messages[1].content); return sseCompletion(JSON.stringify(answer({ ...input(sent.level), kind: sent.kind }, source))); }) as typeof fetch }; const service = new AiService(options); return { service, repository, source, events, options, get calls() { return calls; } }; }

test('A validated streaming response is persisted with original hashes and provider usage; events contain no raw content', async () => { const fixture = setup(); const request = input(); const result = await fixture.service.request(request); assert.equal(result.status, 'completed'); assert.equal(result.snapshot.codeHash, sha256(fixture.source.code)); assert.equal(result.snapshot.runId, 'run-a'); assert.deepEqual(result.usage, { source: 'provider', inputTokens: 10, outputTokens: 20, totalTokens: 30, calls: 1 }); assert.ok(fixture.events.some(event => event.phase === 'receiving')); assert.ok(fixture.events.every(event => event.requestId === request.requestId && !Object.hasOwn(event, 'content') && !Object.hasOwn(event, 'response'))); assert.ok(!canonicalJson(fixture.repository.listAIRequests('attempt-a')).includes('synthetic-unit-key')); });
test('Same complete canonical request can reuse a completed answer, but new question or context cannot', async () => { const fixture = setup(), request = input(); const first = await fixture.service.request(request); const cached = await fixture.service.request({ ...request, requestId: 'request-cache' }); assert.equal(fixture.calls, 1); assert.equal(cached.cachedFromRequestId, first.id); assert.equal(cached.usage, null); await fixture.service.request({ ...request, requestId: 'request-new-question', question: '另一个问题' }); assert.equal(fixture.calls, 2); fixture.source.code += '# change'; fixture.source.run = null; await fixture.service.request({ ...request, requestId: 'request-new-code' }); assert.equal(fixture.calls, 3); });
test('A reused request ID is idempotent and cannot bind a different question', async () => { const fixture = setup(), request = input(); const first = await fixture.service.request(request); fixture.source.code += '# edited after request'; fixture.source.run = null; assert.deepEqual(await fixture.service.request(request), first); assert.equal(fixture.calls, 1); await assert.rejects(fixture.service.request({ ...request, question: 'different' }), error => error instanceof AiServiceError && error.detail.code === 'REQUEST_CONFLICT'); });
test('Concurrent identical IDs create only one provider call', async () => { let calls = 0; const request = input(); const fixture = setup(async () => { calls++; await delay(5); return sseCompletion(JSON.stringify(answer(request))); }); const [first, second] = await Promise.all([fixture.service.request(request), fixture.service.request(request)]); assert.equal(calls, 1); assert.deepEqual(first, second); });
test('One malformed answer is repaired once; raw answer is never stored or emitted', async () => { let calls = 0; const request = input(); const fixture = setup(async (_url, init) => { calls++; const body = JSON.parse(String(init?.body)); if (calls === 2) assert.match(body.messages.at(-1).content, /One format repair only/); return sseCompletion(calls === 1 ? 'UNVALIDATED-MODEL-DATA' : JSON.stringify(answer(request))); }); const result = await fixture.service.request(request); assert.equal(result.status, 'completed'); assert.equal(calls, 2); assert.equal(result.usage?.calls, 2); assert.equal(result.usage?.totalTokens, 60); assert.ok(fixture.events.some(event => event.phase === 'repairing')); assert.ok(!canonicalJson(result).includes('UNVALIDATED-MODEL-DATA')); assert.ok(!canonicalJson(fixture.events).includes('UNVALIDATED-MODEL-DATA')); });
test('Two invalid answers stop without a raw fallback or a third call', async () => { let calls = 0; const fixture = setup(async () => { calls++; return sseCompletion('INVALID-RAW-ANSWER'); }); const result = await fixture.service.request(input()); assert.equal(result.status, 'failed'); assert.equal(result.error?.code, 'FORMAT_INVALID'); assert.equal(calls, 2); assert.equal(result.response, null); assert.ok(!canonicalJson(result).includes('INVALID-RAW-ANSWER')); });
test('L4 and active strict mode are checked before any model call, including a cached request ID', async () => { const fixture = setup(), request = input(); await fixture.service.request(request); fixture.source.mode = 'strict'; await assert.rejects(fixture.service.request(request), error => error instanceof AiServiceError && error.detail.code === 'STRICT_MODE'); fixture.source.mode = 'practice'; await assert.rejects(fixture.service.request({ ...input('L4'), unlockCompleteSolution: false }), error => error instanceof AiServiceError && error.detail.code === 'L4_LOCKED'); assert.equal(fixture.calls, 1); });
test('A strict-mode change during a call suppresses its late answer', async () => { const request = input(); let release!: () => void; const ready = new Promise<void>(resolve => { release = resolve; }); const fixture = setup(async () => { await ready; return sseCompletion(JSON.stringify(answer(request))); }); const pending = fixture.service.request(request); await delay(5); fixture.source.mode = 'strict'; release(); const result = await pending; assert.equal(result.status, 'failed'); assert.equal(result.error?.code, 'STRICT_MODE'); assert.equal(result.response, null); });
test('Late provider completion after cancel cannot overwrite cancelled state', async () => { const request = input(); let release!: () => void; const gate = new Promise<void>(resolve => { release = resolve; }); const fixture = setup(async () => { await gate; return sseCompletion(JSON.stringify(answer(request))); }); const pending = fixture.service.request(request); await delay(5); fixture.service.cancel(request.requestId); const cancelled = await pending; assert.equal(cancelled.status, 'cancelled'); assert.equal(cancelled.response, null); release(); await delay(5); assert.equal(fixture.repository.getAIRequest(request.requestId)!.status, 'cancelled'); assert.ok(!fixture.events.some(event => event.phase === 'completed')); });
test('A response stays with its original request and code if the user edits during generation', async () => { const request = input(); let release!: () => void; const gate = new Promise<void>(resolve => { release = resolve; }); const fixture = setup(async () => { await gate; return sseCompletion(JSON.stringify(answer(request))); }); const originalHash = sha256(fixture.source.code); const pending = fixture.service.request(request); await delay(5); fixture.source.code += '# later edit'; fixture.source.run = null; release(); const result = await pending; assert.equal(result.status, 'completed'); assert.equal(result.snapshot.codeHash, originalHash); assert.ok(fixture.events.every(event => event.codeHash === originalHash)); });
test('Stopped context preparation cannot create an AI record or later call the provider', async () => { const fixture = setup(); let release!: () => void; const gate = new Promise<void>(resolve => { release = resolve; }); fixture.options.resolveContext = async () => { await gate; return fixture.source; }; const service = new AiService(fixture.options); const request = input(); const pending = service.request(request); service.cancel(request.requestId); await assert.rejects(pending, error => error instanceof AiServiceError && error.detail.code === 'CANCELLED'); release(); await delay(1); assert.equal(fixture.repository.records.size, 0); assert.equal(fixture.calls, 0); });
test('Connection capability checks are cancellable through stopAll and late probes cannot pass', async () => { let release!: () => void; const gate = new Promise<void>(resolve => { release = resolve; }); const fixture = setup(async () => { await gate; return jsonCompletion('{"ok":true}'); }); const pending = fixture.service.testConnection(); await delay(5); await fixture.service.stopAll(); const result = await pending; assert.equal(result.status, 'failed'); assert.equal(result.error?.code, 'CANCELLED'); release(); await delay(1); assert.equal(result.status, 'failed'); assert.equal(fixture.repository.records.size, 0); });
test('Connection capability check reports actual fallback transport and missing usage honestly', async () => { const fixture = setup(async () => jsonCompletion('{"ok":true}', false)); const result = await fixture.service.testConnection(); assert.equal(result.status, 'passed'); assert.equal(result.streaming, false); assert.equal(result.structuredOutput, true); assert.equal(result.usageAvailable, false); assert.equal(result.usage, null); });
test('Unconfigured model and credentials never cause a provider call', async () => { const fixture = setup(); fixture.options.resolveProvider = () => null; const service = new AiService(fixture.options); assert.equal((await service.testConnection()).status, 'not-configured'); await assert.rejects(service.request(input()), error => error instanceof AiServiceError && error.detail.code === 'NOT_CONFIGURED'); assert.equal(fixture.calls, 0); const second = setup(); second.options.vault.withKey = async () => { throw new AiServiceError('NOT_CONFIGURED'); }; const result = await new AiService(second.options).request(input()); assert.equal(result.error?.code, 'NOT_CONFIGURED'); assert.equal(second.calls, 0); });
test('Patch is only prepared; stale code or inactive Attempt blocks applying it', async () => { const request = { ...input('L3'), kind: 'diagnosis' as const }; const source = context(); const response = answer(request, source); response.patch = { baseCodeHash: sha256(source.code), edits: [{ startLine: 6, endLine: 6, replacement: '        return total' }] }; const fixture = setup(async () => sseCompletion(JSON.stringify(response))); const record = await fixture.service.request(request); assert.equal(record.status, 'completed'); const proposed = await fixture.service.preparePatch(record.id); assert.match(proposed.code, /return total/); assert.equal(proposed.expectedDraftRevision, 1); assert.equal(fixture.source.code, source.code); fixture.source.code += '# user edited'; fixture.source.run = null; await assert.rejects(fixture.service.preparePatch(record.id), error => error instanceof AiServiceError && error.detail.code === 'STALE_PATCH'); fixture.source.code = source.code; fixture.source.isActive = false; await assert.rejects(fixture.service.preparePatch(record.id), error => error instanceof AiServiceError && error.detail.code === 'STALE_PATCH'); });
test('Credential echoes are rejected without putting the Key into a repair prompt or persistent state', async () => { let calls = 0; const request = input(); const response = answer(request); response.explanation = 'synthetic-unit-key-12345'; const fixture = setup(async () => { calls++; return sseCompletion(JSON.stringify(response)); }); const result = await fixture.service.request(request); assert.equal(result.status, 'failed'); assert.equal(result.error?.code, 'POLICY_VIOLATION'); assert.equal(calls, 1); assert.ok(!canonicalJson(result).includes('synthetic-unit-key-12345')); });
test('Recovered pending requests become interrupted and are never reused as completed cache', async () => { const fixture = setup(), request = input(); const snapshot = buildRequestSnapshot(request, fixture.source, config()); fixture.repository.beginAIRequest({ id: request.requestId, attemptId: request.attemptId, requestHash: requestHash(snapshot), snapshot }); assert.equal(fixture.service.recoverInterrupted(), 1); const recovered = await fixture.service.request(request); assert.equal(recovered.status, 'interrupted'); assert.equal(fixture.calls, 0); await fixture.service.request({ ...request, requestId: 'retry-new-request' }); assert.equal(fixture.calls, 1); });
test('Corrupted completed snapshots and answers are not published as cached or idempotent responses', async () => { const fixture = setup(), request = input(); const first = await fixture.service.request(request); const saved = fixture.repository.records.get(first.id)!; saved.snapshot.messages[1].content += 'corruption'; await assert.rejects(fixture.service.request(request), error => error instanceof AiServiceError && error.detail.code === 'STORAGE'); const replacement = await fixture.service.request({ ...request, requestId: 'after-corrupt-cache' }); assert.equal(replacement.status, 'completed'); assert.equal(replacement.cachedFromRequestId, null); assert.equal(fixture.calls, 2); const latest = fixture.repository.records.get(replacement.id)!; latest.response!.explanation = '```python\nreturn answer\n```'; await assert.rejects(fixture.service.request({ ...request, requestId: latest.id }), error => error instanceof AiServiceError && error.detail.code === 'STORAGE'); });
test('Resolver exception details cannot escape through request or provider configuration APIs', async () => { const fixture = setup(); fixture.options.resolveContext = () => { throw new Error('synthetic-sensitive-context-error'); }; const service = new AiService(fixture.options); await assert.rejects(service.request(input()), error => error instanceof AiServiceError && error.detail.code === 'INVALID_REQUEST' && !error.message.includes('synthetic-sensitive')); fixture.options.resolveProvider = () => { throw new Error('synthetic-sensitive-provider-error'); }; await assert.rejects(service.providerState(), error => error instanceof AiServiceError && error.detail.code === 'INVALID_CONFIG' && !error.message.includes('synthetic-sensitive')); });
