import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CredentialVault, AiServiceError, type SafeStorageLike } from '../../src/ai/index.ts';
import { config } from './helpers.ts';

// Deliberately synthetic reversible transform: verifies the adapter contract, not OS/keychain security.
function safeStorage(available = true): SafeStorageLike { return { isEncryptionAvailable: () => available, encryptString: value => Buffer.from(Buffer.from(value).map(byte => byte ^ 0xa5)), decryptString: value => Buffer.from(value.map(byte => byte ^ 0xa5)).toString('utf8') }; }
async function setup() { const root = await mkdtemp(join(tmpdir(), 'AlgoPractice-AI-vault-test-')); return { root, directory: join(root, 'credentials') }; }
const key = 'synthetic-vault-key-not-a-real-credential';
test('Vault persists only an encrypted envelope, hasKey is boolean, and keys survive a new vault instance', async () => { const files = await setup(); try { const vault = new CredentialVault({ directory: files.directory, safeStorage: safeStorage(), platform: 'darwin' }); assert.equal(await vault.hasKey(config()), false); assert.deepEqual(await vault.setKey(config(), key), { hasKey: true }); assert.equal(await vault.hasKey(config()), true); const entries = await readdir(files.directory); assert.equal(entries.length, 1); const raw = await readFile(join(files.directory, entries[0]), 'utf8'); assert.ok(!raw.includes(key)); assert.ok(!raw.includes('key":"')); assert.deepEqual(Object.keys(JSON.parse(raw)).sort(), ['bindingHash', 'ciphertext', 'schemaVersion']); assert.equal((await stat(join(files.directory, entries[0]))).mode & 0o777, 0o600); const reopened = new CredentialVault({ directory: files.directory, safeStorage: safeStorage(), platform: 'darwin' }); assert.equal(await reopened.withKey(config(), async value => value === key), true); await reopened.clearKey(config()); assert.equal(await vault.hasKey(config()), false); } finally { await rm(files.root, { recursive: true, force: true }); } });
test('Provider identity and canonical endpoint both bind each credential', async () => { const files = await setup(); try { const vault = new CredentialVault({ directory: files.directory, safeStorage: safeStorage(), platform: 'darwin' }); await vault.setKey(config(), key); assert.equal(await vault.hasKey({ ...config(), baseUrl: 'https://another.invalid/v1' }), false); assert.equal(await vault.hasKey({ ...config(), id: 'other-provider' }), false); assert.equal(await vault.hasKey({ ...config(), baseUrl: config().baseUrl + '/chat/completions' }), true); await assert.rejects(vault.withKey({ ...config(), baseUrl: 'https://another.invalid/v1' }, async () => true), error => error instanceof AiServiceError && error.detail.code === 'NOT_CONFIGURED'); } finally { await rm(files.root, { recursive: true, force: true }); } });
test('Unavailable OS encryption and basic_text never fall back to plaintext', async () => { for (const backend of ['unavailable', 'basic_text']) { const files = await setup(); try { const storage = safeStorage(backend !== 'unavailable'); storage.getSelectedStorageBackend = () => 'basic_text'; const vault = new CredentialVault({ directory: files.directory, safeStorage: storage, platform: backend === 'basic_text' ? 'linux' : 'darwin' }); assert.equal(await vault.secureStorageAvailable(), false); await assert.rejects(vault.setKey(config(), key), error => error instanceof AiServiceError && error.detail.code === 'CREDENTIAL_UNAVAILABLE'); await assert.rejects(readdir(files.directory), { code: 'ENOENT' }); } finally { await rm(files.root, { recursive: true, force: true }); } } });
test('Credential decryption failures and malformed files expose only a fixed error', async () => { const files = await setup(); try { const storage = safeStorage(), vault = new CredentialVault({ directory: files.directory, safeStorage: storage, platform: 'darwin' }); await vault.setKey(config(), key); storage.decryptString = () => { throw new Error('secret-provider-message'); }; await assert.rejects(vault.withKey(config(), async () => true), error => { assert.ok(error instanceof AiServiceError); assert.ok(!String(error).includes('secret-provider-message')); return true; }); const entry = (await readdir(files.directory))[0]; await writeFile(join(files.directory, entry), 'malformed-secret'); await assert.rejects(vault.hasKey(config()), error => error instanceof AiServiceError && !String(error).includes('malformed-secret')); } finally { await rm(files.root, { recursive: true, force: true }); } });
test('Asynchronous safeStorage methods are preferred when available', async () => { const files = await setup(); try { const storage = safeStorage(); let syncCalls = 0, asyncCalls = 0; const encrypt = storage.encryptString, decrypt = storage.decryptString; storage.isAsyncEncryptionAvailable = async () => true; storage.encryptStringAsync = async value => { asyncCalls++; return encrypt(value); }; storage.decryptStringAsync = async value => { asyncCalls++; return { result: decrypt(value), shouldReEncrypt: false }; }; storage.encryptString = () => { syncCalls++; throw new Error('sync must not run'); }; storage.decryptString = () => { syncCalls++; throw new Error('sync must not run'); }; const vault = new CredentialVault({ directory: files.directory, safeStorage: storage, platform: 'darwin' }); await vault.setKey(config(), key); assert.equal(await vault.withKey(config(), async value => value === key), true); assert.equal(syncCalls, 0); assert.equal(asyncCalls, 2); } finally { await rm(files.root, { recursive: true, force: true }); } });
test('Newline credentials are rejected before writing and replacements do not leave partial files', async () => { const files = await setup(); try { const vault = new CredentialVault({ directory: files.directory, safeStorage: safeStorage(), platform: 'darwin' }); await assert.rejects(vault.setKey(config(), 'value\nInjected: header'), error => error instanceof AiServiceError && error.detail.code === 'INVALID_REQUEST'); await vault.setKey(config(), key); await vault.setKey(config(), key + '-replacement'); assert.equal(await vault.withKey(config(), async value => value.endsWith('-replacement')), true); assert.equal((await readdir(files.directory)).length, 1); } finally { await rm(files.root, { recursive: true, force: true }); } });
