import { useEffect, useState } from 'react';
import type { DesktopBridge, Page } from '../shared/bridge';
import type { InterviewRules, InterviewPool, CompanyPreview } from '../shared/interview';
import { defaultInterviewRules } from '../shared/interview';
import { dateTime, errorText } from './ui';
import { flushPendingSaves, setEditsFrozen } from './pending-saves';
import { InterviewWorkbench } from './InterviewWorkbench';

type State = Awaited<ReturnType<DesktopBridge['interviewState']>>;
export function InterviewPage({api,onError,onNavigate}:{api:DesktopBridge|undefined;onError:(message:string)=>void;onNavigate:(page:Page)=>void}) {
  const [state,setState]=useState<State>({active:null,history:[],datasets:[]});
  const [rules,setRules]=useState<InterviewRules>(()=>({...defaultInterviewRules,counts:{...defaultInterviewRules.counts},seed:crypto.randomUUID()}));
  const [preview,setPreview]=useState<{id:string;pool:InterviewPool}|null>(null), [company,setCompany]=useState<{id:string;preview:CompanyPreview}|null>(null);
  const [selected,setSelected]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
  const [companyText,setCompanyText]=useState(''),[companyFormat,setCompanyFormat]=useState<'csv'|'json'>('csv');
  async function load(){if(api)setState(await api.interviewState());}
  useEffect(()=>{void load().catch(e=>onError(errorText(e)));},[api]);
  const act=async(name:string,operation:()=>Promise<unknown>)=>{if(busy)return;setBusy(name);setMessage('');try{await operation();}catch(e){onError(errorText(e));}finally{setBusy('');}};
  const update=<K extends keyof InterviewRules>(key:K,value:InterviewRules[K])=>{setRules(r=>({...r,[key]:value}));setPreview(null);};
  const dataset=state.datasets.find(d=>d.id===rules.datasetId);
  if(selected&&api)return <InterviewWorkbench api={api} sessionId={selected} onLeave={()=>{setSelected('');void load();}} />;
  return <section className="interview-page scroll-page"><div className="page-intro"><div><h2>给自己一场真实的限时练习</h2><p>先检查题池，再开始计时。题目和作答都保留本场版本。</p></div></div>
    {state.active&&<div className="interview-resume"><div><strong>有一场面试正在进行</strong><p>计时不会因为离开此页而暂停。</p></div><button className="button primary" onClick={()=>location.reload()}>回到本场面试</button></div>}
    {message&&<p role="status" className="success-text">{message}</p>}
    <div className="interview-setup"><form onSubmit={e=>{e.preventDefault();void act('preview',async()=>{if(api)setPreview(await api.previewInterview(rules));});}}>
      <h3>本场规则</h3><div className="interview-fields"><label>面试模式<select aria-label="面试模式" value={rules.mode} disabled={Boolean(busy||state.active)} onChange={e=>update('mode',e.target.value as InterviewRules['mode'])}><option value="strict">严格模式</option><option value="coached">辅导模式</option></select></label>
      <label>作答语言<select aria-label="面试语言" value={rules.language} disabled={Boolean(busy||state.active)} onChange={e=>update('language',e.target.value as InterviewRules['language'])}><option value="python">Python</option><option value="java">Java</option></select></label>
      <label>时长（分钟）<input aria-label="面试时长" type="number" min={1} max={240} value={rules.durationMinutes} onChange={e=>update('durationMinutes',Number(e.target.value))} /></label>
      <label>排除最近几天练习题<input aria-label="排除近期天数" type="number" min={0} max={365} value={rules.excludeRecentDays} onChange={e=>update('excludeRecentDays',Number(e.target.value))} /></label></div>
      <fieldset className="interview-counts"><legend>难度与题数 · 合计最多 10 道</legend>{(['easy','medium','hard'] as const).map(tier=><label key={tier}>{{easy:'简单',medium:'中等',hard:'困难'}[tier]}<input aria-label={`${{easy:'简单',medium:'中等',hard:'困难'}[tier]}题数`} type="number" min={0} max={10} value={rules.counts[tier]} onChange={e=>update('counts',{...rules.counts,[tier]:Number(e.target.value)})} /></label>)}</fieldset>
      <label className="p3-field">主题（任选其一，逗号分隔）<input value={rules.tags.join(',')} placeholder="留空为全部主题" onChange={e=>update('tags',e.target.value.split(/[,，]/).map(t=>t.trim()).filter(Boolean))} /></label>
      <div className="interview-fields"><label>企业数据集<select aria-label="企业数据集" value={rules.datasetId??''} onChange={e=>{setRules(r=>({...r,datasetId:e.target.value||null,company:null}));setPreview(null);}}><option value="">不限定企业</option>{state.datasets.map(d=><option key={d.id} value={d.id}>{d.name} · {d.fileHash.slice(0,8)}</option>)}</select></label>
      <label>企业<select aria-label="筛选企业" value={rules.company??''} disabled={!dataset} onChange={e=>update('company',e.target.value||null)}><option value="">不限定</option>{[...new Set(dataset?.entries.map(e=>e.normalizedCompany)??[])].map(c=><option key={c}>{c}</option>)}</select></label>
      <label>抽样方式<select aria-label="抽样方式" value={rules.sampling} onChange={e=>update('sampling',e.target.value as InterviewRules['sampling'])}><option value="uniform">按约束均匀抽样</option><option value="frequency">来源频率优先</option></select></label>
      <label>抽样种子<input aria-label="抽样种子" value={rules.seed} maxLength={200} onChange={e=>update('seed',e.target.value)} /></label></div>
      <p className="field-help">严格模式仅开放题面、代码与本地测试。可以中途转为辅导；本场会永久保留转换记录。</p>
      <button className="button primary" disabled={!api||Boolean(busy||state.active)} type="submit">{busy==='preview'?'正在检查…':'检查本场题池'}</button>
    </form><aside className="interview-pool" aria-label="题池检查"><h3>开始之前</h3>{preview?<><p className="interview-pool-count"><strong>{preview.pool.candidates.length}</strong> 道符合条件的题目</p>{preview.pool.shortages.length?<div role="alert" className="interview-shortages"><h4>题池还不够</h4>{preview.pool.shortages.map(text=><p key={text}>{text}</p>)}<p>调整条件后再次检查，不会自动放宽规则。</p></div>:<><p>本场抽取 {preview.pool.selectedIds.length} 道，持续 {rules.durationMinutes} 分钟。</p><button className="button primary" disabled={Boolean(busy||state.active)||!api} onClick={()=>{void act('start',async()=>{if(!api)return;await flushPendingSaves();setEditsFrozen(true,'interview-start');try{await api.startInterview(preview.id,crypto.randomUUID());location.reload();}finally{setEditsFrozen(false,'interview-start');}});}}>{busy==='start'?'正在进入面试…':'开始本场面试'}</button></>}
      <details><summary>查看筛选说明（{preview.pool.exclusions.length}）</summary><ul>{preview.pool.exclusions.map(e=><li key={e.problemId}><span>{e.problemId}</span> · {e.reason}</li>)}</ul></details><p className="field-help">预览保留 10 分钟。同一题池、规则与种子可以复现题序。</p></>:<><p>默认 45 分钟、1 道中等题，排除最近 14 天练习题。</p><p className="field-help">仅链接、缺少语言适配或用例的题目不会入选。可先到题库补全内容。</p><button className="text-button" onClick={()=>onNavigate('library')}>查看题库</button></>}</aside></div>
    <details className="interview-company"><summary>导入企业题单 · CSV / JSON</summary><p>企业名称和题目 URL（或 problemId）必填。数据日期、统计窗口和频率口径未知时保持未知；导入时间不代表数据更新时间。</p>
      <div className="compact-actions"><button className="button" disabled={!api||Boolean(busy||state.active)} onClick={()=>{void act('company-file',async()=>{if(!api)return;const file=await api.selectCompanyFile();if(file){setCompanyText(file.text);setCompanyFormat(file.kind);setCompany(await api.previewCompany(file));}});}}>选择本机企业文件</button><label>文本格式<select value={companyFormat} onChange={e=>{setCompanyFormat(e.target.value as 'csv'|'json');setCompany(null);}}><option value="csv">CSV</option><option value="json">JSON</option></select></label></div>
      <label className="p3-field">或粘贴企业数据<textarea aria-label="企业数据文本" value={companyText} placeholder={'company,url,dataDate,window,frequency,frequencyMeaning\n示例企业,https://leetcode.cn/problems/two-sum/,,,,'} onChange={e=>{setCompanyText(e.target.value);setCompany(null);}} /></label><button className="button" disabled={!api||!companyText.trim()||Boolean(busy||state.active)} onClick={()=>{void act('company-preview',async()=>{if(api)setCompany(await api.previewCompany({kind:companyFormat,text:companyText,name:'粘贴的企业题单'}));});}}>预览企业数据</button>
      {company&&<div className="interview-company-preview"><p>{company.preview.dataset.entries.length} 条有效记录 · 去除 {company.preview.duplicates} 条完全重复记录 · {company.preview.missingProblemIds.length} 道尚未入库</p>{company.preview.errors.map(text=><p role="alert" className="error-text" key={text}>{text}</p>)}<div className="interview-table-scroll"><table><thead><tr><th>原公司名 → 归一名</th><th>题目</th><th>数据日期 / 窗口</th><th>频率 / 口径</th></tr></thead><tbody>{company.preview.dataset.entries.slice(0,100).map((e,i)=><tr key={i}><td>{e.company} → {e.normalizedCompany}</td><td>{e.problemId}</td><td>{e.dataDate??'未知'} / {e.window??'未知'}</td><td>{e.frequency??'未知'} / {e.frequencyMeaning??'未知'}</td></tr>)}</tbody></table></div>{company.preview.dataset.entries.length>100&&<p className="field-help">预览显示前 100 条，确认后保存全部有效记录。</p>}<div className="compact-actions"><button className="button primary" disabled={Boolean(busy)||company.preview.errors.length>0} onClick={()=>{void act('company-commit',async()=>{if(!api)return;const result=await api.commitCompany(company.id);await load();setMessage(`已保存 ${result.name}。`);});}}>确认导入企业数据</button>{company.preview.dataset.entries.some(entry=>entry.url)&&<button className="text-button" disabled={Boolean(busy)||!state.datasets.some(d=>d.id===company.preview.dataset.id)} onClick={()=>{void act('company-complete',async()=>{if(!api)return;await api.completeCompanyProblems(company.preview.dataset.id,crypto.randomUUID());onNavigate('sources');});}}>补全题面与适配</button>}</div><p className="field-help">文件 SHA-256：{company.preview.dataset.fileHash}。确认导入后可用原 URL 补全题面与适配，进度沿用普通导入任务；企业关联会保留。</p></div>}
    </details>
    <section className="interview-history"><h3>面试档案</h3>{state.history.length?<div className="study-list">{state.history.map(row=><button className="study-row" key={row.id} onClick={()=>setSelected(row.id)}><span>{dateTime(row.startedAt)}</span><span>{row.mode==='strict'?'严格':'辅导'} · {row.count} 道题{row.anomalous?' · 计时异常':''}</span><span>查看报告 →</span></button>)}</div>:<p className="field-help">结束一场面试后，冻结代码、运行记录和复盘入口会出现在这里。</p>}</section>
  </section>;
}
