import { useCallback, useEffect, useRef, useState } from 'react';
import type { DesktopBridge, RunArchive } from '../shared/bridge';
import type { InterviewView } from '../shared/interview';
import type { StoredRun } from '../storage/practice-store';
import type { Note, NoteListItem, AttemptListItem } from '../shared/learning';
import { Editor } from './Editor';
import { AiPanel } from './AiPanel';
import { AiSettings } from './AiSettings';
import { Markdown } from './Markdown';
import { Statement, dateTime, errorText, statusText, statusClass, formatValue } from './ui';
import { flushPendingSaves, registerPendingSave, setEditsFrozen, useEditsFrozen } from './pending-saves';

function archive(run:StoredRun):RunArchive|null { if(run.status==='queued'||!run.result)return null;return {...run,result:run.result as unknown as RunArchive['result']}; }
function ReferencePanel({ api, onError }: { api: DesktopBridge; onError: (error: string) => void }) {
  const [notes, setNotes] = useState<NoteListItem[]>([]); const [archives, setArchives] = useState<AttemptListItem[]>([]); const [search, setSearch] = useState('');
  const [notePage, setNotePage] = useState(0); const [archivePage, setArchivePage] = useState(0); const [noteTotal, setNoteTotal] = useState(0); const [archiveTotal, setArchiveTotal] = useState(0);
  const [noteDetails, setNoteDetails] = useState<Record<string, Note>>({}); const [selected, setSelected] = useState(''); const [selectedCode, setSelectedCode] = useState('');
  useEffect(() => { let alive = true; const timer = setTimeout(() => { void Promise.all([api.notePage({ search, offset: notePage * 20, limit: 20 }), api.attemptPage({ search, offset: archivePage * 20, limit: 20 })]).then(([n, a]) => { if (alive) { setNotes(n.items); setNoteTotal(n.total); setArchives(a.items); setArchiveTotal(a.total); } }).catch(error => { if (alive) onError(errorText(error)); }); }, 150); return () => { alive = false; clearTimeout(timer); }; }, [api, search, notePage, archivePage]);
  useEffect(() => { let alive = true; setSelectedCode(''); if (selected) void (async () => { const overview = await api.archiveOverview(selected); let code = overview.attempt.finalCode; if (code === null) { const runs = await api.runPage({ attemptId: selected, limit: 1 }); if (runs.items[0]) code = (await api.runDetail(runs.items[0].id)).code; } if (alive) setSelectedCode(code ?? '此记录没有已保存代码。'); })().catch(error => { if (alive) onError(errorText(error)); }); return () => { alive = false; }; }, [api, selected]);
  return <section aria-label="参考资料"><h3>笔记与历史解法</h3><p className="field-help">查看参考资料会记入本场帮助记录。</p><label className="p3-field">搜索参考资料<input type="search" aria-label="搜索参考资料" value={search} onChange={event => { setSearch(event.target.value); setNotePage(0); setArchivePage(0); setSelected(''); }} /></label>
    {notes.map(note => <details key={note.id} onToggle={event => { if (event.currentTarget.open && !noteDetails[note.id]) void api.note(note.id).then(value => { if (value) setNoteDetails(previous => ({ ...previous, [note.id]: value })); }).catch(error => onError(errorText(error))); }}><summary>{note.current.title}</summary>{noteDetails[note.id] ? <Markdown text={noteDetails[note.id].confirmed?.markdown ?? noteDetails[note.id].current.markdown} /> : <p>正在读取笔记…</p>}</details>)}
    <div className="pagination"><span>{noteTotal} 篇笔记 · 第 {notePage + 1} 页</span><button disabled={!notePage} onClick={() => setNotePage(notePage - 1)}>上一页笔记</button><button disabled={(notePage + 1) * 20 >= noteTotal} onClick={() => setNotePage(notePage + 1)}>下一页笔记</button></div>
    <label className="p3-field">历史练习<select aria-label="面试参考历史" value={selected} onChange={event => setSelected(event.target.value)}><option value="">选择历史记录</option>{archives.map(row => <option key={row.attempt.id} value={row.attempt.id}>{row.title} · {dateTime(row.attempt.startedAt)}</option>)}</select></label>
    <div className="pagination"><span>{archiveTotal} 次练习 · 第 {archivePage + 1} 页</span><button disabled={!archivePage} onClick={() => { setArchivePage(archivePage - 1); setSelected(''); }}>上一页档案</button><button disabled={(archivePage + 1) * 20 >= archiveTotal} onClick={() => { setArchivePage(archivePage + 1); setSelected(''); }}>下一页档案</button></div>{selected && <pre className="archive-code">{selectedCode || '正在读取代码…'}</pre>}
  </section>;
}
const supplementRun=(run:StoredRun)=>Boolean(run.testSnapshot&&typeof run.testSnapshot==='object'&&!Array.isArray(run.testSnapshot)&&run.testSnapshot.interviewSupplement===true);
interface BufferState { code:string; reasoning:string; dirty:boolean; }
export function InterviewWorkbench({api,sessionId,onLeave}:{api:DesktopBridge;sessionId:string;onLeave:()=>void}){
  const [view,setView]=useState<InterviewView|null>(null),[index,setIndex]=useState(0),[error,setError]=useState(''),[message,setMessage]=useState('');
  const [code,setCode]=useState(''),[reasoning,setReasoning]=useState(''),[saving,setSaving]=useState('已保存到本机');
  const [running,setRunning]=useState(false),[busy,setBusy]=useState(false),[panel,setPanel]=useState<'runs'|'ai'|'references'|'settings'>('runs');
  const [recap,setRecap]=useState(false),[confirm,setConfirm]=useState<'finish'|'coach'|null>(null);
  const buffers=useRef(new Map<string,BufferState>()),currentId=useRef(''),currentView=useRef<InterviewView|null>(null);currentView.current=view;
  const initialized=useRef(false),queue=useRef(Promise.resolve()),timer=useRef<ReturnType<typeof setTimeout>|null>(null),maximum=useRef<ReturnType<typeof setTimeout>|null>(null),runBusy=useRef(false);
  const frozen=useEditsFrozen(); const selected=view?.items[index],ended=Boolean(view?.session.endedAt),strict=view?.session.mode==='strict'&&!ended;
  const refresh=useCallback(async()=>{const next=await api.interview(sessionId);setView(next);currentView.current=next;if(!initialized.current){for(const row of next.items)buffers.current.set(row.item.problem.id,{code:(next.session.endedAt?row.item.final!:row.item.accepted).code,reasoning:(next.session.endedAt?row.item.final!:row.item.accepted).reasoning,dirty:false});initialized.current=true;const first=next.items[0];currentId.current=first.item.problem.id;setCode(buffers.current.get(currentId.current)!.code);setReasoning(buffers.current.get(currentId.current)!.reasoning);}return next;},[api,sessionId]);
  const flush=useCallback(async()=>{
    if(timer.current)clearTimeout(timer.current);if(maximum.current){clearTimeout(maximum.current);maximum.current=null;}
    const pending=[...buffers.current.entries()].filter(([,buffer])=>buffer.dirty).map(([id,buffer])=>({id,...buffer}));
    if(!pending.length)return queue.current;
    for(const snapshot of pending)buffers.current.get(snapshot.id)!.dirty=false;
    const operation=queue.current.catch(()=>{}).then(async()=>{for(const snapshot of pending){try{
      const saved=await api.saveInterview(sessionId,snapshot.id,snapshot.code,snapshot.reasoning);
      if(currentId.current===snapshot.id&&buffers.current.get(snapshot.id)?.code===snapshot.code){setSaving(saved.counted?'已确认保存 · 计入本场':'已保存复盘草稿 · 不计入本场');if(!saved.counted)setMessage('本场已冻结。截止后输入已保留为复盘草稿。');}
    }catch(e){const buffer=buffers.current.get(snapshot.id);if(buffer)buffer.dirty=true;setSaving('保存失败');setError(errorText(e));throw e;}}});queue.current=operation;return operation;
  },[api,sessionId]);
  useEffect(()=>registerPendingSave(`interview:${sessionId}`,flush),[flush,sessionId]);
  useEffect(()=>{let alive=true;void refresh().catch(e=>{if(alive)setError(errorText(e));});const poll=setInterval(()=>{if(!currentView.current?.session.endedAt)void refresh().catch(e=>{if(alive)setError(errorText(e));});},1000);const remove=api.onLibraryChanged(()=>{void refresh().catch(e=>{if(alive)setError(errorText(e));});});return()=>{alive=false;clearInterval(poll);remove();if(timer.current)clearTimeout(timer.current);if(maximum.current)clearTimeout(maximum.current);};},[refresh,api]);
  useEffect(()=>{if(ended){void flush().catch(()=>{});setRecap(false);setConfirm(null);}},[ended,flush]);
  useEffect(()=>api.onClosing(()=>{setEditsFrozen(true);void flushPendingSaves().then(()=>api.closeReady()).catch(e=>setError(errorText(e))).finally(()=>setEditsFrozen(false));}),[api]);
  useEffect(()=>{const remove=api.onMaintenance(id=>{setEditsFrozen(true,'maintenance');void flushPendingSaves().then(()=>api.maintenanceReady(id)).catch(e=>api.maintenanceReady(id,errorText(e)));});const end=api.onMaintenanceEnd(()=>setEditsFrozen(false,'maintenance'));return()=>{remove();end();};},[api]);
  function edit(value:string,kind:'code'|'reasoning'){
    if(frozen||busy||(ended&&!recap))return;const buffer=buffers.current.get(currentId.current);if(!buffer)return;buffer[kind]=value;buffer.dirty=true;if(kind==='code')setCode(value);else setReasoning(value);setSaving('尚未保存');
    if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{void flush().catch(()=>{});},500);if(!maximum.current)maximum.current=setTimeout(()=>{void flush().catch(()=>{});},2000);
  }
  async function choose(next:number){if(busy)return;setBusy(true);try{await flush();setIndex(next);setRecap(false);const id=currentView.current!.items[next].item.problem.id;currentId.current=id;const buffer=buffers.current.get(id)!;setCode(buffer.code);setReasoning(buffer.reasoning);setSaving('已保存到本机');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function run(supplement=false){if(runBusy.current||!selected||frozen)return;runBusy.current=true;setRunning(true);setError('');try{await flush();await api.runInterview(sessionId,selected.item.problem.id,crypto.randomUUID(),supplement);await refresh();}catch(e){setError(errorText(e));}finally{runBusy.current=false;setRunning(false);}}
  async function end(){setBusy(true);try{await flush();setView(await api.finishInterview(sessionId));setConfirm(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function coach(){setBusy(true);try{await flush();setView(await api.coachInterview(sessionId));setConfirm(null);setMessage('已转为辅导模式，本场保留转换记录。');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  if(!view||!selected)return <section className="scroll-page"><p role="status">正在恢复面试快照…</p>{error&&<p role="alert">{error}</p>}</section>;
  const session=view.session,item=selected.item,problem=item.problem.content,final=item.final;
  const displayCode=ended&&!recap?final!.code:code,displayReasoning=ended&&!recap?final!.reasoning:reasoning;
  const matching=selected.runs.filter(run=>run.codeHash===(final?.codeHash??item.accepted.codeHash));const latest=matching.filter(run=>run.status!=='queued').at(-1);
  const latestResult=latest?archive(latest):null;const seconds=Math.ceil(view.remainingMs/1000);const timerText=`${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`;
  const reportAttempt={...selected.attempt,mode:session.mode};
  return <section className="interview-workbench scroll-page" aria-label="面试工作台"><div className="interview-session-head"><div><p className="interview-mode">{ended?'本场已冻结':strict?'严格面试':'辅导面试'}{session.modeChanges.length>0?' · 由严格模式转入':''}</p><h2>{ended?'回看本场，找到下一步':'专注眼前这一题'}</h2><p>{dateTime(session.startedAt)} · {session.pool.rules.language==='python'?'Python':'Java'} · {session.items.length} 道题</p></div><div className="interview-clock"><span>{ended?'本场用时':'剩余时间'}</span><strong aria-label="面试剩余时间">{ended?`${Math.round((Date.parse(session.endedAt!)-Date.parse(session.startedAt))/1000)} 秒`:timerText}</strong><span>{ended?(session.endReason==='manual'?'主动结束':session.endReason==='deadline'?'时间到':'计时异常'):'后台和休眠期间继续计时'}</span></div></div>
    {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>setError('')}>收起</button></div>}{message&&<p className="interview-message" role="status">{message}</p>}
    {session.clockAnomalies.length>0&&<div className="interview-shortages" role="alert"><strong>本场计时异常</strong><p>作答快照已冻结，本场不作为可靠限时成绩。</p>{session.clockAnomalies.map(text=><p key={text}>{text}</p>)}</div>}
    <div className="interview-actions"><div className="interview-item-tabs" aria-label="本场题目">{session.items.map((row,i)=><button className={i===index?'selected':''} aria-pressed={i===index} disabled={busy||frozen} key={row.problem.id} onClick={()=>{void choose(i);}}>第 {i+1} 题</button>)}</div><div className="compact-actions">{!ended&&strict&&<button className="text-button" disabled={busy||frozen} onClick={()=>setConfirm('coach')}>转为辅导模式</button>}{!ended?<button className="button" disabled={busy||frozen} onClick={()=>setConfirm('finish')}>结束本场</button>:<button className="button" disabled={busy||frozen} onClick={()=>{void flush().then(onLeave).catch(e=>setError(errorText(e)));}}>返回面试列表</button>}</div></div>
    {confirm&&<div className="interview-confirm" role="alertdialog" aria-label={confirm==='finish'?'确认结束面试':'确认转为辅导'}><h3>{confirm==='finish'?'结束并冻结本场作答？':'转为辅导模式？'}</h3><p>{confirm==='finish'?'已保存的作答将成为本场依据。之后的修改另存为复盘草稿。':'可以查看笔记和 AI 帮助，计时继续。本场无法再恢复“全程严格”标记。'}</p><div className="compact-actions"><button className="button primary" disabled={busy} onClick={()=>{void(confirm==='finish'?end():coach());}}>{confirm==='finish'?'确认结束并冻结':'确认转为辅导'}</button><button className="text-button" disabled={busy} onClick={()=>setConfirm(null)}>继续当前模式</button></div></div>}
    {ended&&<div className="interview-report" aria-label="本场确定性报告"><div><h3>第 {index+1} 题 · {problem.title}</h3><p>{latest?`冻结代码：${latest.status==='interrupted'?'运行已中断':statusText[latest.status as keyof typeof statusText]}`:'冻结代码尚未取得测试结果'}{matching.some(run=>run.status==='queued')?' · 有运行等待结果':''}</p><p className="field-help">{problem.cases.length} 个本地用例；本地通过不等于官方 AC。旧代码结果不会替代冻结代码的结果。</p></div><dl><dt>最终修订</dt><dd>r{final!.revision} · {final!.codeHash.slice(0,12)}</dd><dt>确认保存时间</dt><dd>{dateTime(final!.savedAt)}</dd><dt>帮助记录</dt><dd>{session.help.length} 次参考访问 · {session.modeChanges.length} 次模式转换</dd><dt>本场 AI 帮助</dt><dd>{selected.aiHelp.filter(help=>help.duringSession).length} 次已完成回答{selected.aiHelp.some(help=>help.duringSession)?` · 最高 ${selected.aiHelp.filter(help=>help.duringSession).map(help=>help.level).sort().at(-1)}`:''}</dd><dt>文字思路</dt><dd>{final!.reasoning.trim()?'有记录，可用于 AI 复盘':'未采集，不评表达能力'}</dd></dl><div className="compact-actions"><button className="button" disabled={busy||frozen} onClick={()=>{void api.reviewInterview(sessionId,item.problem.id).then(()=>setMessage('已加入该语言的重写复习；重复加入不会产生重复评分。')).catch(e=>setError(errorText(e)));}}>加入重写复习</button><button className="text-button" disabled={busy||frozen} onClick={()=>{const next=selected.recap?.code??final!.code,nextReasoning=selected.recapReasoning??final!.reasoning;buffers.current.set(item.problem.id,{code:next,reasoning:nextReasoning,dirty:false});setCode(next);setReasoning(nextReasoning);setRecap(true);}}>编辑复盘草稿</button></div>
      <details><summary>本场规则与固定资料</summary><p>算法版本：{session.pool.algorithmVersion} · 种子：{session.pool.rules.seed}</p><p>候选 {session.pool.candidates.length} 道；题序：{session.pool.selectedIds.join(' → ')}</p>{session.pool.dataset&&<p>企业数据：{session.pool.dataset.name} · 文件 SHA-256 {session.pool.dataset.fileHash}</p>}<p>题面版本：{item.problem.version}</p>{session.help.map((help,i)=><p key={i}>{dateTime(help.at)} · {help.kind}</p>)}</details>
    </div>}
    <div className="interview-grid"><section className="interview-statement"><h3>{problem.title}</h3><Statement content={problem}/>{strict&&<p className="field-help">严格模式仅提供题面事实与术语说明；不开放 AI 解题澄清。</p>}</section><section className="interview-coding"><div className="editor-toolbar"><span>{ended?(recap?'复盘草稿 · 不计入本场':'本场冻结代码'):saving}</span><div className="run-actions">{running?<button className="button" onClick={()=>{void api.cancel().catch(e=>setError(errorText(e)));}}>停止运行</button>:<button className="button primary" disabled={busy||frozen} onClick={()=>{void run(ended);}}>{ended?'补测冻结代码':'运行本地测试'}</button>}</div></div><div className="interview-editor"><Editor key={`${item.problem.id}:${recap?'recap':'answer'}`} code={displayCode} language={session.pool.rules.language} readOnly={busy||frozen||(ended&&!recap)} onChange={value=>edit(value,'code')} onRun={()=>{void run(ended);}} diagnostics={latestResult?.code===displayCode?latestResult.result.diagnostics:[]} /></div><label className="p3-field interview-reasoning">文字思路（可选）<textarea aria-label="面试文字思路" value={displayReasoning} maxLength={12000} disabled={busy||frozen||(ended&&!recap)} placeholder="记录你的思路、边界条件与取舍；未记录时不评价表达能力。" onChange={e=>edit(e.target.value,'reasoning')} /></label>{saving==='保存失败'&&<button className="button" onClick={()=>{void flush();}}>重试保存</button>}
      <section className="interview-results" aria-label="面试测试结果"><h3>当前{ended?'冻结':''}代码的测试</h3>{latestResult?<><p className={statusClass(latestResult.result.status)}>{statusText[latestResult.result.status]}</p><p className="field-help">{session.endedAt&&supplementRun(latest!)?'结束后补测':session.endedAt&&latest!.finishedAt&&Date.parse(latest!.finishedAt)>Date.parse(session.endedAt)?'截止前发起，结束后返回':'本地公开用例'}</p>{latestResult.result.caseResults.map(test=><details key={test.index}><summary>用例 {test.index+1} · {statusText[test.status]}</summary><pre>实际：{formatValue(test.actual)}{`\n`}期望：{formatValue(test.expected)}</pre></details>)}{latestResult.result.diagnostics.map((diagnostic,i)=><pre className="diagnostic" key={i}>{diagnostic.message}</pre>)}</>:<p className="field-help">这个代码版本还没有完成的测试结果。</p>}</section>
    </section></div>
    <section className="interview-bottom"><div className="panel-tabs"><button aria-pressed={panel==='runs'} onClick={()=>setPanel('runs')}>本场运行记录</button>{!strict&&<><button aria-pressed={panel==='ai'} onClick={()=>setPanel('ai')}>{ended?'AI 复盘':'AI 分级帮助'}</button><button aria-pressed={panel==='references'} onClick={()=>setPanel('references')}>参考笔记与解法</button></>}</div>
      {panel==='runs'&&<div className="interview-runs">{selected.runs.length?selected.runs.map((run,i)=><details key={run.id}><summary>运行 {i+1} · {run.status==='queued'?'正在运行':statusText[run.status]} · {run.codeHash===(final?.codeHash??item.accepted.codeHash)?'当前快照':'历史快照'}</summary><p className="field-help">{dateTime(run.createdAt)} · {run.codeHash.slice(0,12)}{session.endedAt&&supplementRun(run)?' · 结束后补测':''}</p><pre className="archive-code">{run.code}</pre></details>):<p className="field-help">本场还没有运行记录。</p>}</div>}
      {!strict&&panel==='ai'&&<AiPanel key={item.attemptId} api={api} attempt={reportAttempt} code={ended?final!.code:code} selectedRun={latestResult} reviewMode={ended} flush={flush} onApply={async request=>{await flush();const result=await api.applyInterviewPatch(sessionId,request);if(!result.counted)throw new Error('面试已截止，修改只保留为复盘草稿。');buffers.current.set(item.problem.id,{code:result.answer.code,reasoning:result.answer.reasoning,dirty:false});setCode(result.answer.code);await refresh();}} onNoteSaved={()=>setMessage('AI 提案已保存为待确认笔记，可在学习笔记中查看。')} onSettings={()=>setPanel('settings')} onError={setError}/>}
      {!strict&&panel==='references'&&<ReferencePanel api={api} onError={setError}/>}{!strict&&panel==='settings'&&<AiSettings api={api} onError={setError}/>}</section>
  </section>;
}
