import { useEffect, useState } from 'react';
import type { BackupState, DesktopBridge, PreparedRestore } from '../shared/bridge';
import type { ReminderSettings } from '../shared/maintenance';
import { DEFAULT_REMINDER_SETTINGS } from '../shared/maintenance';
import { AiSettings } from './AiSettings';
import { dateTime, errorText } from './ui';
import { useEditsFrozen, flushPendingSaves } from './pending-saves';
export function LearningSettingsPage({ api, onError }: { api: DesktopBridge | undefined; onError: (message: string) => void }) {
  const [budget, setBudget] = useState('3'); const [zone, setZone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone);
  const [reminders, setReminders] = useState<ReminderSettings>(DEFAULT_REMINDER_SETTINGS); const [backups, setBackups] = useState<BackupState | null>(null);
  const [restore, setRestore] = useState<PreparedRestore | null>(null); const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const frozen = useEditsFrozen();
  useEffect(() => { let alive = true; if (api) void Promise.all([api.learningSettings(), api.reminderState()]).then(([settings, reminder]) => { if (alive) { setBudget(settings.dailyReviewBudget === null ? '' : String(settings.dailyReviewBudget)); setZone(settings.timeZone); setReminders(reminder.settings); } }).catch(error => onError(errorText(error))); return () => { alive = false; }; }, [api]);
  useEffect(() => { if (!api) return; let alive = true; let timer: ReturnType<typeof setTimeout> | null = null; let loading = false; const refresh = async () => { if (loading) return; loading = true; try { const state = await api.backups(); if (!alive) return; setBackups(previous => ({ ...state, backups: state.busy && previous ? previous.backups : state.backups })); if (state.busy) timer = setTimeout(() => { void refresh(); }, 1000); } catch (error) { if (alive) onError(errorText(error)); } finally { loading = false; } }; const remove = api.onLibraryChanged(() => { void refresh(); }); void refresh(); return () => { alive = false; remove(); if (timer) clearTimeout(timer); }; }, [api]);
  async function action(name: string, operation: () => Promise<void>) { if (busy || frozen) return; setBusy(name); setMessage(''); try { await operation(); } catch (error) { onError(errorText(error)); } finally { setBusy(''); } }
  return <section className="learning-page scroll-page"><div className="page-intro"><div><h2>按自己的节奏学习</h2><p>安排复习、连接 AI，并管理本机数据的备份与恢复。</p></div></div>
    <section className="settings-section learning-section"><h3>每日复习</h3><form className="p3-form" onSubmit={event => { event.preventDefault(); void action('learning', async () => { if (!api) return; const value = await api.saveLearningSettings({ dailyReviewBudget: budget.trim() ? Number(budget) : null, timeZone: zone }); setBudget(value.dailyReviewBudget === null ? '' : String(value.dailyReviewBudget)); setZone(value.timeZone); setMessage('复习预算和时区已保存。'); }); }}><div className="form-columns"><label className="p3-field">每日复习预算<input type="number" min={0} max={1000} value={budget} placeholder="留空表示不限制" disabled={Boolean(busy) || frozen} onChange={event => setBudget(event.target.value)} /></label><label className="p3-field">IANA 时区<input value={zone} placeholder="Asia/Shanghai" disabled={Boolean(busy) || frozen} onChange={event => setZone(event.target.value)} /></label></div><p className="field-help">默认每天 3 项。预算用完后，其余到期项目继续保留；时区决定今日统计和提醒时间。</p><button className="button" disabled={!api || Boolean(busy) || frozen} type="submit">保存复习设置</button></form></section>
    <section className="settings-section learning-section"><h3>系统复习提醒</h3><form className="p3-form" onSubmit={event => { event.preventDefault(); void action('reminders', async () => { if (!api) return; const value = await api.saveReminderSettings(reminders); setReminders(value.settings); setMessage('复习提醒已保存。'); }); }}><label className="checkbox-field"><input type="checkbox" checked={reminders.enabled} disabled={Boolean(busy) || frozen} onChange={event => setReminders(value => ({ ...value, enabled: event.target.checked }))} />开启每日聚合提醒</label><div className="form-columns"><label className="p3-field">提醒时间<input type="time" value={reminders.at} disabled={Boolean(busy) || frozen} onChange={event => setReminders(value => ({ ...value, at: event.target.value }))} /></label><label className="p3-field">稍后提醒（分钟）<input type="number" min={1} max={240} value={reminders.snoozeMinutes} disabled={Boolean(busy) || frozen} onChange={event => setReminders(value => ({ ...value, snoozeMinutes: Number(event.target.value) }))} /></label><label className="p3-field">安静时段开始<input type="time" value={reminders.quietStart} disabled={Boolean(busy) || frozen} onChange={event => setReminders(value => ({ ...value, quietStart: event.target.value }))} /></label><label className="p3-field">安静时段结束<input type="time" value={reminders.quietEnd} disabled={Boolean(busy) || frozen} onChange={event => setReminders(value => ({ ...value, quietEnd: event.target.value }))} /></label></div><p className="field-help">默认 20:00 提醒，22:00–08:00 保持安静，稍后提醒为 30 分钟。完全退出应用后不发送；下次打开会显示逾期状态。</p><button className="button" disabled={!api || Boolean(busy) || frozen} type="submit">保存提醒设置</button></form></section>
    <AiSettings api={api} onError={onError} />
    <section className="settings-section learning-section backup-settings"><h3>备份与恢复</h3><p>备份包含题目、练习、笔记、复习记录、附件和可移植设置。应用在数据变化后每天自动备份，保留最近 7 份；手动备份单独保留。</p><p className="field-help">API Key、站点登录会话、运行时和日志不包含在备份中。恢复后需要重新配置密钥和站点登录。</p><div className="compact-actions"><button className="button" disabled={!api || Boolean(busy) || frozen || backups?.busy} onClick={() => { void action('backup', async () => { await flushPendingSaves(); const value = await api!.createBackup(); if (value) { setMessage(`备份已保存：${value.path}`); setBackups(await api!.backups()); } }); }}>{busy === 'backup' ? '正在生成备份…' : '创建手动备份'}</button><button className="button" disabled={!api || Boolean(busy) || frozen || backups?.busy} onClick={() => { void action('inspect', async () => { setRestore(await api!.previewRestore()); }); }}>选择备份并检查</button><button className="text-button" disabled={!api || Boolean(busy) || frozen} onClick={() => { void action('refresh', async () => { setBackups(await api!.backups()); }); }}>刷新备份列表</button></div>
    {backups?.lastError && <p className="error-text" role="alert">{backups.lastError}</p>}<div className="study-list">{backups?.backups.map(backup => <div className="study-row" key={backup.manifest.id}><div><h4>{backup.manifest.kind === 'automatic' ? '自动备份' : backup.manifest.kind === 'before-restore' ? '恢复前备份' : '手动备份'} · {dateTime(backup.manifest.createdAt)}</h4><p>{(backup.bytes / 1048576).toFixed(2)} MiB · 数据版本 {backup.manifest.databaseVersion}</p><p className="path-value">{backup.path}</p></div></div>)}</div>{backups?.busy && <p className="field-help" role="status">正在生成或检查备份，完成后列表会自动更新。</p>}{backups && !backups.busy && !backups.backups.length && <p className="field-help">应用备份目录中暂时没有已验证的备份。</p>}
    {restore && <div className="review-rating" role="alertdialog" aria-label="确认恢复备份"><h3>恢复 {dateTime(restore.manifest.createdAt)} 的备份？</h3><p>已检查清单与文件校验值。将保存当前草稿、停止运行与 AI 请求，并在替换当前数据前创建恢复前备份。</p><p>此操作会用所选备份替换当前学习数据，并清除当前 AI 密钥与站点会话。需要的当前内容可从恢复前备份找回。</p><dl className="system-details"><dt>应用版本</dt><dd>{restore.manifest.appVersion}</dd><dt>数据版本</dt><dd>{restore.manifest.databaseVersion}</dd><dt>文件数</dt><dd>{restore.manifest.files.length}</dd><dt>大小</dt><dd>{(restore.bytes / 1048576).toFixed(2)} MiB</dd></dl><div className="compact-actions"><button className="button primary" disabled={Boolean(busy) || frozen} onClick={() => { void action('restore', async () => { await api!.restoreBackup(restore.id); setRestore(null); }); }}>{busy === 'restore' ? '正在恢复并重新打开…' : '确认替换并恢复'}</button><button className="text-button" disabled={Boolean(busy)} onClick={() => setRestore(null)}>取消</button></div></div>}
    </section>{message && <p className="success-text" role="status">{message}</p>}
  </section>;
}
