import { useCallback, useEffect, useRef, useState } from 'react';
import type { DesktopBridge, LibraryIndex } from '../shared/bridge';
import type { Note, NoteListItem, NoteVersion, SaveNoteInput, ProblemListItem } from '../shared/learning';
import { dateTime, errorText } from './ui';
import { ProblemPicker } from './ProblemPicker';
import { Markdown } from './Markdown';
import { editsFrozen, registerPendingSave, useEditsFrozen } from './pending-saves';

type EditorState = { noteId: string; kind: 'problem' | 'topic'; subjectId: string; title: string; markdown: string; tags: string; attachmentHashes: string[]; version: number; state: 'draft' | 'confirmed' };
const fromNote = (note: Note): EditorState => ({ noteId: note.id, kind: note.kind, subjectId: note.subjectId, title: note.current.title, markdown: note.current.markdown, tags: note.current.tags.join('，'), attachmentHashes: note.current.attachmentHashes, version: note.latestVersion, state: note.current.state });
export function NotesPage({ api, library, initialSubject, onError }: { api: DesktopBridge | undefined; library: LibraryIndex; initialSubject?: string; onError: (message: string) => void }) {
  const [notes, setNotes] = useState<NoteListItem[]>([]); const [search, setSearch] = useState(''); const [tag, setTag] = useState('');
  const [page, setPage] = useState(0); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [historyOpen, setHistoryOpen] = useState(false);
  const [editor, setEditor] = useState<EditorState | null>(null); const current = useRef<EditorState | null>(null);
  const [versions, setVersions] = useState<NoteVersion[]>([]); const [viewVersion, setViewVersion] = useState<number | null>(null);
  const [status, setStatus] = useState(''); const [busy, setBusy] = useState(''); const [deleteOpen, setDeleteOpen] = useState(false);
  const dirty = useRef(0); const saved = useRef(0); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); const inFlight = useRef<Promise<void> | null>(null);
  const attachmentTask = useRef<Promise<void> | null>(null);
  const maxWait = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pending = useRef<{ revision: number; input: SaveNoteInput } | null>(null); const mounted = useRef(true); const frozen = useEditsFrozen();
  const listGeneration = useRef(0);
  const refresh = useCallback(async () => { if (!api) return; const generation = ++listGeneration.current; setLoading(true); try { const result = await api.notePage({ search, tag: tag || undefined, offset: page * 30, limit: 30 }); if (mounted.current && generation === listGeneration.current) { setNotes(result.items); setTotal(result.total); if (page && !result.items.length) setPage(Math.max(0, Math.ceil(result.total / 30) - 1)); } } finally { if (mounted.current && generation === listGeneration.current) setLoading(false); } }, [api, search, tag, page]);
  const refreshRef = useRef(refresh); refreshRef.current = refresh;
  const flush = useCallback(async () => {
    if (timer.current) { clearTimeout(timer.current); timer.current = null; }
    if (maxWait.current) { clearTimeout(maxWait.current); maxWait.current = null; }
    if (inFlight.current) await inFlight.current;
    if (!api || !current.current || dirty.current === saved.current) return;
    const task = (async () => {
      while (current.current && dirty.current !== saved.current) {
        const snapshot = current.current;
        pending.current ??= { revision: dirty.current, input: { requestId: crypto.randomUUID(), ...(snapshot.noteId ? { noteId: snapshot.noteId, expectedVersion: snapshot.version } : {}), kind: snapshot.kind, subjectId: snapshot.subjectId, title: snapshot.title, markdown: snapshot.markdown, tags: snapshot.tags.split(/[,，]/).map(value => value.trim()).filter(Boolean), attachmentHashes: snapshot.attachmentHashes, origin: 'user', state: 'draft' } };
        const submission = pending.current; if (mounted.current) setStatus('正在保存草稿…');
        try {
          const note = await api.saveNote(submission.input); saved.current = submission.revision; pending.current = null;
          current.current = { ...current.current!, noteId: note.id, version: note.latestVersion, state: note.current.state };
          if (mounted.current) { setEditor(current.current); setStatus('草稿已保存'); setNotes(rows => rows.map(row => row.id === note.id ? { ...row, latestVersion: note.latestVersion, confirmedVersion: note.confirmedVersion, updatedAt: note.updatedAt, current: { ...row.current, title: note.current.title, tags: note.current.tags, state: note.current.state, version: note.current.version } } : row)); }
        } catch (error) { if (errorText(error).includes('NOTE_WRITE_REJECTED:')) pending.current = null; if (mounted.current) setStatus('保存失败，请重试'); throw error; }
      }
    })();
    inFlight.current = task; try { await task; } finally { if (inFlight.current === task) inFlight.current = null; }
  }, [api]);
  useEffect(() => { mounted.current = true; const remove = registerPendingSave('Markdown 笔记草稿', async () => { await attachmentTask.current; await flush(); }); return () => { mounted.current = false; remove(); if (timer.current) clearTimeout(timer.current); if (maxWait.current) clearTimeout(maxWait.current); }; }, [flush]);
  useEffect(() => { const timer = setTimeout(() => { void refresh().catch(error => onError(errorText(error))); }, search || tag ? 150 : 0); const off = api?.onLibraryChanged(() => { void refresh().catch(error => onError(errorText(error))); }); return () => { listGeneration.current++; clearTimeout(timer); off?.(); }; }, [api, refresh]);
  useEffect(() => { let alive = true; if (historyOpen && editor?.noteId && api) void api.noteVersions(editor.noteId).then(rows => { if (alive) setVersions(rows); }).catch(error => onError(errorText(error))); else setVersions([]); return () => { alive = false; }; }, [api, editor?.noteId, editor?.version, historyOpen]);
  function edit(patch: Partial<EditorState>) { if (!current.current || editsFrozen() || busy) return; if ((patch.subjectId !== undefined || patch.kind !== undefined) && (current.current.noteId || pending.current)) return; current.current = { ...current.current, ...patch, state: 'draft' }; setEditor(current.current); dirty.current++; setStatus('有未保存修改'); setViewVersion(null); if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => { void flush().catch(error => onError(errorText(error))); }, 700); if (!maxWait.current) maxWait.current = setTimeout(() => { void flush().catch(error => onError(errorText(error))); }, 2000); }
  async function select(note?: NoteListItem, kind: 'problem' | 'topic' = 'problem') {
    if (busy || frozen) return; setBusy('switch');
    try { await flush(); const detail = note ? await api?.note(note.id) : null; if (note && !detail) throw new Error('笔记已经不存在，请刷新列表。'); setHistoryOpen(false); const next = detail ? fromNote(detail) : { noteId: '', kind, subjectId: kind === 'topic' ? '算法专题' : initialSubject || library.problems[0]?.id || '', title: '未命名笔记', markdown: '', tags: '', attachmentHashes: [], version: 0, state: 'draft' as const }; current.current = next; setEditor(next); dirty.current = 0; saved.current = 0; pending.current = null; setViewVersion(null); setStatus(note ? '本机版本已读取' : '编辑后自动保存为草稿'); } catch (error) { onError(errorText(error)); } finally { setBusy(''); }
  }
  async function confirm() { if (!api || busy || frozen) return; setBusy('confirm'); try { await flush(); const value = current.current; if (!value?.noteId) return; const note = await api.confirmNote({ requestId: crypto.randomUUID(), noteId: value.noteId, version: value.version, expectedVersion: value.version }); current.current = fromNote(note); setEditor(current.current); setStatus('此版本已确认'); await refreshRef.current(); } catch (error) { onError(errorText(error)); } finally { setBusy(''); } }
  async function attach() {
    if (!api || busy || frozen || !editor || attachmentTask.current) return; setBusy('attach');
    const task = (async () => { try { const attachment = await api.addAttachment(); if (attachment && current.current) { const value = current.current; current.current = { ...value, attachmentHashes: [...new Set([...value.attachmentHashes, attachment.hash])], markdown: value.markdown + `\n\n${attachment.mimeType.startsWith('image/') ? '!' : ''}[${attachment.name.replace(/[\[\]\\]/g, '_')}](algopractice://app/attachment/${attachment.hash})\n` }; setEditor(current.current); dirty.current++; await flush(); } } catch (error) { onError(errorText(error)); throw error; } finally { setBusy(''); } })();
    attachmentTask.current = task; try { await task; } catch { /* Error stays visible; a waiting save barrier receives the rejection. */ } finally { if (attachmentTask.current === task) attachmentTask.current = null; }
  }
  async function removeNote() { if (!api || !editor?.noteId || busy || frozen) return; setBusy('delete'); try { await flush(); await api.deleteNote(editor.noteId, current.current!.version); current.current = null; setEditor(null); dirty.current = saved.current = 0; setDeleteOpen(false); await refreshRef.current(); } catch (error) { onError(errorText(error)); } finally { setBusy(''); } }
  const visible = notes;
  const shown = versions.find(version => version.version === viewVersion);
  const [problemRows, setProblemRows] = useState<ProblemListItem[]>([]);
  const subjectIds = [...new Set(notes.filter(note => note.kind === 'problem').map(note => note.subjectId))].sort().join('\n');
  useEffect(() => { let alive = true; if (api && subjectIds) void api.problemPage({ ids: subjectIds.split('\n'), limit: 100 }).then(value => { if (alive) setProblemRows(value.items); }).catch(error => { if (alive) onError(errorText(error)); }); return () => { alive = false; }; }, [api, subjectIds, library]);
  const problemTitles = new Map([...library.problems, ...problemRows].map(problem => [problem.id, problem.content.title]));
  const allTags = [...new Set(notes.flatMap(note => note.current.tags))].sort();
  const totalPages = Math.max(1, Math.ceil(total / 30));
  return <section className="learning-page scroll-page"><div className="page-intro"><div><h2>把思路写下来，留给下次回忆</h2><p>题目笔记和专题笔记支持 Markdown。草稿自动保存，确认后的版本可以供 AI 引用。</p></div><div className="compact-actions"><button className="button" disabled={!api || frozen || Boolean(busy) || !library.totalProblems} onClick={() => { void select(); }}>新建题目笔记</button><button className="button" disabled={!api || frozen || Boolean(busy)} onClick={() => { void select(undefined, 'topic'); }}>新建专题笔记</button></div></div>
    <div className="library-filters"><label className="search-field">搜索笔记<input type="search" value={search} placeholder="标题、正文或标签" onChange={event => { setSearch(event.target.value); setPage(0); }} /></label><label>标签<input aria-label="筛选笔记标签" list="note-tags" value={tag} placeholder="输入完整标签" onChange={event => { setTag(event.target.value); setPage(0); }} /><datalist id="note-tags">{allTags.map(value => <option key={value} value={value} />)}</datalist></label></div>
    <div className="pagination"><span>{total} 篇笔记 · 第 {page + 1} / {totalPages} 页{loading ? ' · 正在读取…' : ''}</span><button disabled={loading || page === 0} onClick={() => setPage(page - 1)}>上一页</button><button disabled={loading || (page + 1) * 30 >= total} onClick={() => setPage(page + 1)}>下一页</button></div>
    <div className="notes-layout"><aside className="notes-list" aria-label="笔记列表">{visible.map(note => <button key={note.id} className={editor?.noteId === note.id ? 'selected' : ''} disabled={Boolean(busy) || frozen} onClick={() => { void select(note); }}><strong>{note.current.title}</strong><span>{note.kind === 'problem' ? problemTitles.get(note.subjectId) || note.subjectId : note.subjectId}</span><span>v{note.latestVersion} · {note.current.state === 'confirmed' ? '已确认' : note.current.origin === 'ai' ? 'AI 草稿，待确认' : '草稿'} · {dateTime(note.updatedAt)}</span></button>)}{!visible.length && <p className="empty-state">还没有匹配的笔记。</p>}</aside>
      {editor ? <div className="note-editor"><div className="form-columns"><label className="p3-field">标题<input aria-label="笔记标题" value={editor.title} maxLength={300} disabled={Boolean(busy) || frozen} onChange={event => edit({ title: event.target.value })} /></label>{editor.kind === 'problem' ? <ProblemPicker api={api} value={editor.subjectId} disabled={Boolean(editor.noteId) || Boolean(pending.current) || Boolean(busy) || frozen} onChange={id => edit({ subjectId: id })} onError={onError} /> : <label className="p3-field">专题名称<input value={editor.subjectId} disabled={Boolean(editor.noteId) || Boolean(pending.current) || Boolean(busy) || frozen} onChange={event => edit({ subjectId: event.target.value })} /></label>}</div>
      <label className="p3-field">标签（逗号分隔）<input value={editor.tags} disabled={Boolean(busy) || frozen} onChange={event => edit({ tags: event.target.value })} /></label><label className="p3-field">Markdown 正文<textarea className="note-body" aria-label="Markdown 正文" value={editor.markdown} rows={16} spellCheck={false} disabled={Boolean(busy) || frozen} onChange={event => edit({ markdown: event.target.value })} /></label>
      <div className="compact-actions"><span role="status" className={status.startsWith('保存失败') ? 'error-text' : 'local-status'}>{status}</span><button className="text-button" disabled={Boolean(busy) || frozen} onClick={() => { void flush().catch(error => onError(errorText(error))); }}>立即保存</button><button className="button" disabled={Boolean(busy) || frozen} onClick={() => { void attach(); }}>添加本机附件</button><button className="button primary" disabled={Boolean(busy) || frozen || !editor.noteId || (editor.state === 'confirmed' && saved.current === dirty.current)} onClick={() => { void confirm(); }}>确认当前版本</button><button className="text-button" disabled={Boolean(busy) || frozen || !editor.noteId} onClick={() => { void flush().then(() => api?.exportNote(current.current!.noteId, current.current!.version)).catch(error => onError(errorText(error))); }}>导出 Markdown 与附件</button></div>
      <section className="note-preview"><h3>当前草稿预览</h3><Markdown text={editor.markdown} onOpenLink={url => { void api?.openWebLink(url).catch(error => onError(errorText(error))); }} onAttachment={hash => { void api?.exportAttachment(hash).catch(error => onError(errorText(error))); }} /></section>
      <details className="note-history" open={historyOpen} onToggle={event => setHistoryOpen(event.currentTarget.open)}><summary>历史版本（{versions.length}）</summary><label className="p3-field">查看版本<select value={viewVersion ?? ''} onChange={event => setViewVersion(Number(event.target.value) || null)}><option value="">选择历史版本</option>{versions.map(version => <option key={version.version} value={version.version}>v{version.version} · {version.state === 'confirmed' ? '已确认' : '草稿'} · {version.origin === 'ai' ? 'AI' : '手动'} · {dateTime(version.createdAt)}</option>)}</select></label>{shown && <div><h4>{shown.title}</h4><Markdown text={shown.markdown} onAttachment={hash => { void api?.exportAttachment(hash).catch(error => onError(errorText(error))); }} /><button className="text-button" disabled={Boolean(busy) || frozen} onClick={() => edit({ title: shown.title, markdown: shown.markdown, tags: shown.tags.join('，'), attachmentHashes: shown.attachmentHashes })}>以此版本继续编辑</button></div>}</details>
      {editor.noteId && <button className="text-button danger-text" disabled={Boolean(busy) || frozen} onClick={() => setDeleteOpen(true)}>删除这篇笔记</button>}{deleteOpen && <div className="review-rating" role="alertdialog" aria-label="确认删除笔记"><h3>删除「{editor.title}」及其所有版本？</h3><p>档案中的此笔记关联也会移除。此前已发送给 AI 的引用内容仍随对应对话档案保留，已有备份也需要单独管理。</p><button className="button" disabled={Boolean(busy) || frozen} onClick={() => { void removeNote(); }}>确认删除笔记</button><button className="text-button" disabled={Boolean(busy)} onClick={() => setDeleteOpen(false)}>取消</button></div>}
      </div> : <div className="empty-state"><h3>选择一篇笔记，或开始记录</h3><p>AI 总结保存后也会先作为草稿出现在这里。</p></div>}
    </div>
  </section>;
}
