import { useCallback, useEffect, useId, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import type { DesktopBridge } from '../shared/bridge';
import type { Note, NoteListItem, PageResult, ProblemListItem } from '../shared/learning';
import type { ProblemReviewBatchInput, ProblemReviewDetail, ProblemReviewEvent, ProblemReviewStatus, ReviewOpportunity, ReviewPlanListItem, ReviewPlanQuery, ReviewPlanSnapshot, ReviewSession } from '../shared/review-plan';
import { makeReviewPracticeSource, makeReviewSessionPracticeSource, type PracticeNavigationSource } from '../shared/practice-navigation';
import { archiveDateBoundary } from '../shared/archive-date';
import { difficultyLabel } from '../shared/presentation';
import { addDays, monthGrid, shiftMonth } from './learning-calendar';
import { errorText, Icon } from './ui';
import { useEditsFrozen } from './pending-saves';
import { Markdown } from './Markdown';
import { ProblemReviewRating, problemRatings, type ProblemReviewRatingMode } from './ProblemReviewRating';
import { HelpHint } from './HelpHint';
import './review-plan.css';

export interface ReviewPlanPageProps {
  api: DesktopBridge | undefined; onPractice: (problemId: string, session?: ReviewSession, source?: PracticeNavigationSource) => void | Promise<void>;
  onChanged: () => void | Promise<void>; onError: (message: string) => void; refreshToken?: number;
  onNotes?: (problemId: string) => void; onArchives?: (problemId: string) => void;
}
const statusLabels: Record<ProblemReviewStatus, string> = { unassessed: '待首次评估', due: '到期', overdue: '逾期', scheduled: '已安排', suspended: '已暂停', pending: '待补评' };
const sourceLabels = { manual: '主动自评', official: '官方 AC', legacy: '迁移历史' };
const legacyTargetLabel = (target: string) => target === 'rewrite' ? '重写' : '思路';
const legacyLanguageLabel = (language: string) => language === 'none' ? '不分语言' : language || '未指定语言';
const ratingLabel = (value: number | null) => problemRatings.find(row => row.value === value)?.title ?? '尚未自评';
const dateLabel = (date: string) => `${Number(date.slice(5, 7))}/${Number(date.slice(-2))}`;
const monthLabel = (month: string) => `${month.slice(0, 4)} 年 ${Number(month.slice(5))} 月`;
const instantLabel = (at: string | null, zone: string) => at ? new Intl.DateTimeFormat('zh-CN', { timeZone: zone, month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(at)) : '—';
const emptyPage = <T,>(): PageResult<T> => ({ items: [], total: 0, offset: 0, limit: 20, hasMore: false });

function PageNumbers({ page, busy, onPage }: { page: PageResult<unknown>; busy?: boolean; onPage: (offset: number) => void }) {
  return <div className="review-pagination"><span>{page.total ? `${page.offset + 1}–${Math.min(page.offset + page.items.length, page.total)} / ${page.total}` : '0 题'}</span><div><button className="button" disabled={busy || page.offset === 0} onClick={() => onPage(Math.max(0, page.offset - page.limit))}>上一页</button><button className="button" disabled={busy || !page.hasMore} onClick={() => onPage(page.offset + page.limit)}>下一页</button></div></div>;
}
function PlanDialog({ title, children, busy, onClose }: { title: string; children: ReactNode; busy: boolean; onClose: () => void }) {
  const element = useRef<HTMLDialogElement>(null), heading = useId();
  useEffect(() => { const previous = document.activeElement instanceof HTMLElement ? document.activeElement : null; const dialog = element.current; if (dialog && !dialog.open) dialog.showModal(); return () => { dialog?.close(); if (previous?.isConnected) previous.focus({ preventScroll: true }); }; }, []);
  return <dialog ref={element} className="review-plan-dialog" aria-labelledby={heading} onCancel={event => { event.preventDefault(); if (!busy) onClose(); }}><div className="review-panel-heading"><h2 id={heading}>{title}</h2><button className="review-close" aria-label={`关闭${title}`} disabled={busy} onClick={onClose}>×</button></div>{children}</dialog>;
}

function AddReviewDialog({ api, onClose, onAdded, onError }: { api: DesktopBridge; onClose: () => void; onAdded: () => Promise<void>; onError: (message: string) => void }) {
  const [search, setSearch] = useState(''), [page, setPage] = useState(emptyPage<ProblemListItem>), [offset, setOffset] = useState(0);
  const [selected, setSelected] = useState(new Set<string>()), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [failure, setFailure] = useState('');
  const working = useRef(false); const frozen = useEditsFrozen();
  useEffect(() => { let alive = true; setLoading(true); const timer = setTimeout(() => { void api.problemPage({ search, offset, limit: 20 }).then(value => { if (alive) { setPage(value); setFailure(''); } }).catch(error => { if (alive) setFailure(errorText(error)); }).finally(() => { if (alive) setLoading(false); }); }, 150); return () => { alive = false; clearTimeout(timer); }; }, [api, search, offset]);
  async function add() {
    if (working.current || frozen || !selected.size) return; working.current = true; setBusy(true); setFailure('');
    try { await api.addProblemReviews({ problemIds: [...selected] }); await onAdded(); onClose(); }
    catch (error) { setFailure(errorText(error)); onError(errorText(error)); }
    finally { working.current = false; setBusy(false); }
  }
  return <PlanDialog title="添加复习题目" busy={busy || frozen} onClose={onClose}><label className="review-field">搜索题目<input type="search" value={search} placeholder="题名、编号或标签" disabled={busy || frozen} onChange={event => { setSearch(event.target.value); setOffset(0); }} /></label>
    {failure && <p className="review-error" role="alert">{failure}</p>}<div className="review-add-list" aria-busy={loading}>{loading ? <p>正在读取题库…</p> : page.items.map(row => <label className="review-add-row" key={row.id}><input type="checkbox" checked={selected.has(row.id)} disabled={busy || frozen || (!selected.has(row.id) && selected.size >= 100)} onChange={event => { const checked = event.currentTarget.checked; setSelected(previous => { const next = new Set(previous); if (checked) next.add(row.id); else next.delete(row.id); return next; }); }} /><span><strong>{row.content.title}</strong><small>{difficultyLabel(row.content.difficulty)} · {row.content.tags.join('、') || '暂无主题'}</small></span></label>)}{!loading && !page.total && !failure && <p>没有匹配题目。请缩小筛选，或先导入题目。</p>}</div>
    <PageNumbers page={page} busy={loading || busy} onPage={setOffset} /><footer className="review-dialog-actions"><span>已选 {selected.size} 题（最多 100 题）</span><div><button className="button" disabled={busy || frozen} onClick={onClose}>取消</button><button className="button primary" disabled={busy || frozen || !selected.size} onClick={() => { void add(); }}>{busy ? '正在添加…' : `添加 ${selected.size || ''} 题`}</button></div></footer>
  </PlanDialog>;
}

export function ReviewPlanPage({ api, onPractice, onChanged, onError, refreshToken, onNotes, onArchives }: ReviewPlanPageProps) {
  const budgetInputId = useId();
  const [query, setQuery] = useState<ReviewPlanQuery>({ view: 'today', sort: 'due', offset: 0, limit: 20 });
  const [search, setSearch] = useState(''), [snapshot, setSnapshot] = useState<ReviewPlanSnapshot | null>(null);
  const [session, setSession] = useState<ReviewSession | null>(null), [loading, setLoading] = useState(true), [failure, setFailure] = useState('');
  const [busy, setBusy] = useState(''), [message, setMessage] = useState(''), [selection, setSelection] = useState(new Map<string, number>());
  const [addOpen, setAddOpen] = useState(false), [budgetOpen, setBudgetOpen] = useState(false), [budget, setBudget] = useState('3');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [deferOpen, setDeferOpen] = useState(false), [deferDate, setDeferDate] = useState('');
  const [detailId, setDetailId] = useState(''), [detail, setDetail] = useState<ProblemReviewDetail | null>(null), [historyOffset, setHistoryOffset] = useState(0);
  const [detailPracticeSource, setDetailPracticeSource] = useState<PracticeNavigationSource | null>(null);
  const [detailLoading, setDetailLoading] = useState(false), [detailFailure, setDetailFailure] = useState(''), [notes, setNotes] = useState<NoteListItem[] | null>(null);
  const [openedNote, setOpenedNote] = useState<Note | null>(null), [opportunityOffset, setOpportunityOffset] = useState(0);
  const [opportunities, setOpportunities] = useState(emptyPage<ReviewOpportunity>), [opportunityLoading, setOpportunityLoading] = useState(false);
  const [recallOpen, setRecallOpen] = useState(false), [ratingMode, setRatingMode] = useState<ProblemReviewRatingMode | null>(null);
  const generation = useRef(0), detailGeneration = useRef(0), working = useRef(false), startRequest = useRef<string | null>(null);
  const listHeading = useRef<HTMLHeadingElement>(null), detailHeading = useRef<HTMLHeadingElement>(null), previousDetailFocus = useRef<HTMLElement | null>(null);
  const rowButtons = useRef(new Map<string, HTMLButtonElement>());
  const frozen = useEditsFrozen(); const callbacks = useRef({ onError, onChanged, onPractice }); callbacks.current = { onError, onChanged, onPractice };

  const load = useCallback(async () => {
    if (!api) { setLoading(false); return; }
    const current = ++generation.current; setLoading(true);
    try {
      const [value, ongoing] = await Promise.all([api.reviewPlan(query), api.reviewSession()]);
      if (current !== generation.current) return;
      if (value.items.offset > 0 && !value.items.items.length && value.items.total > 0) { setQuery(previous => ({ ...previous, offset: Math.max(0, value.items.offset - value.items.limit) })); return; }
      setSnapshot(value); setSession(ongoing?.status === 'active' ? ongoing : null); setFailure('');
    } catch (error) { if (current === generation.current) { setFailure(errorText(error)); callbacks.current.onError(errorText(error)); } }
    finally { if (current === generation.current) setLoading(false); }
  }, [api, query]);
  useEffect(() => { void load(); let timer: ReturnType<typeof setTimeout> | undefined; const remove = api?.onLibraryChanged(() => { if (!timer) timer = setTimeout(() => { timer = undefined; void load(); }, 150); }); const interval = setInterval(() => { if (document.visibilityState === 'visible') void load(); }, 60000); return () => { generation.current++; remove?.(); clearTimeout(timer); clearInterval(interval); }; }, [api, load, refreshToken]);
  useEffect(() => { const timer = setTimeout(() => { setQuery(previous => previous.search === search ? previous : { ...previous, search: search || undefined, offset: 0 }); setSelection(new Map()); }, 200); return () => clearTimeout(timer); }, [search]);
  const loadDetail = useCallback(async () => {
    if (!api || !detailId) return; const current = ++detailGeneration.current; setDetailLoading(true);
    try { const value = await api.problemReviewDetail(detailId, { offset: historyOffset, limit: 20 }); if (current === detailGeneration.current) { setDetail(value); setDetailFailure(''); } }
    catch (error) { if (current === detailGeneration.current) setDetailFailure(errorText(error)); }
    finally { if (current === detailGeneration.current) setDetailLoading(false); }
  }, [api, detailId, historyOffset]);
  useEffect(() => { void loadDetail(); return () => { detailGeneration.current++; }; }, [loadDetail, snapshot?.snapshotVersion]);
  useEffect(() => { if (!api || !detailId) return; let alive = true; setOpportunityLoading(true); void api.reviewOpportunities({ problemId: detailId, pendingOnly: true, offset: opportunityOffset, limit: 10 }).then(page => { if (alive) { setOpportunities(page); if (page.offset > 0 && !page.items.length) setOpportunityOffset(Math.max(0, page.offset - page.limit)); } }).catch(error => { if (alive) setDetailFailure(errorText(error)); }).finally(() => { if (alive) setOpportunityLoading(false); }); return () => { alive = false; }; }, [api, detailId, opportunityOffset, snapshot?.snapshotVersion]);
  useEffect(() => { if (detailId) detailHeading.current?.focus({ preventScroll: false }); }, [detailId]);
  const summary = snapshot?.summary, view = query.view ?? 'today'; const rows = snapshot?.items ?? emptyPage<ReviewPlanListItem>();
  const today = summary?.date, zone = summary?.timeZone ?? 'UTC'; const month = query.month ?? today?.slice(0, 7);
  const dayMap = new Map(snapshot?.calendar.map(row => [row.date, row]) ?? []);
  const changed = useCallback(async () => { await load(); await loadDetail(); await callbacks.current.onChanged(); }, [load, loadDetail]);
  function filter(patch: Partial<ReviewPlanQuery>) { if (patch.view && patch.view !== query.view) setFiltersOpen(patch.view !== 'today'); setQuery(previous => ({ ...previous, ...patch, offset: 0 })); setSelection(new Map()); setDeferOpen(false); }
  function selectDate(date: string) { filter({ view: 'calendar', date, month: date.slice(0, 7), status: undefined }); requestAnimationFrame(() => listHeading.current?.focus()); }
  function openDetail(row: ReviewPlanListItem, origin: HTMLElement) { previousDetailFocus.current = origin; const entryQuery = snapshot?.query ?? query; setDetailPracticeSource(makeReviewPracticeSource(entryQuery, entryQuery.view === 'today' ? '今日复习列表' : entryQuery.date ? `${entryQuery.date} 复习列表` : '复习列表')); setDetail(null); setDetailId(row.problemId); setHistoryOffset(0); setNotes(null); setOpenedNote(null); setOpportunityOffset(0); setOpportunities(emptyPage()); setRecallOpen(false); setDetailFailure(''); }
  function closeDetail() { const problemId = detailId; setDetailId(''); setDetail(null); setRatingMode(null); requestAnimationFrame(() => { const origin = previousDetailFocus.current; const target = origin?.isConnected ? origin : rowButtons.current.get(problemId) ?? listHeading.current; target?.focus({ preventScroll: true }); }); }
  async function action(name: string, task: () => Promise<void>) {
    if (working.current || frozen) return; working.current = true; setBusy(name); setMessage('');
    try { await task(); } catch (error) { setMessage(''); setFailure(errorText(error)); callbacks.current.onError(errorText(error)); }
    finally { working.current = false; setBusy(''); }
  }
  async function begin(problemIds?: string[], source?: PracticeNavigationSource) {
    if (!api) return; await action('session', async () => {
      startRequest.current ??= crypto.randomUUID();
      const value = !problemIds && session ? await api.reviewSession(session.id) : await api.startReviewSession({ requestId: startRequest.current, ...(problemIds ? { problemIds } : {}) });
      if (!value?.currentProblemId || value.status !== 'active') { setSession(null); await load(); setMessage('本轮暂无可开始的题目，请查看待评估或待补评记录。'); return; }
      startRequest.current = null; setSession(value); await callbacks.current.onPractice(value.currentProblemId, value, source ?? makeReviewSessionPracticeSource(value));
    });
  }
  async function batch(patch: Pick<ProblemReviewBatchInput, 'suspended' | 'scheduledAt'>, name: string) {
    if (!api || !selection.size) return; await action(name, async () => { await api.updateProblemReviews({ problemIds: [...selection.keys()], expectedRevisions: Object.fromEntries(selection), ...patch }); setSelection(new Map()); setDeferOpen(false); await changed(); setMessage(`已更新 ${selection.size} 道题的安排。`); });
  }
  function selectPage(checked: boolean) { setSelection(previous => { const next = new Map(previous); for (const row of rows.items) { if (checked) next.set(row.problemId, row.revision); else next.delete(row.problemId); } return next; }); }
  async function loadNotes() { if (!api || !detail) return; await action('notes', async () => { const page = await api.notePage({ kind: 'problem', subjectId: detail.plan.problemId, limit: 20 }); setNotes(page.items); }); }
  const canBegin = Boolean(api && summary && ((session?.currentProblemId) || summary.plannedCount > 0));
  const budgetNumber = summary?.budget, ratio = budgetNumber ? Math.min(1, (summary?.reviewedToday ?? 0) / budgetNumber) : 0;
  const latestEvents = detail?.events.items.filter(event => event.kind === 'review') ?? [];
  const counts = problemRatings.map(option => ({ ...option, count: latestEvents.filter(event => event.effectiveRating === option.value).length }));
  const actionTitle = !summary ? '正在读取复习安排…' : summary.plannedCount > 0 ? <>待复习 <strong>{summary.plannedCount}</strong> 题</> : summary.remainingBudget === 0 ? '今日推荐量已完成' : summary.deferredCount > 0 ? '今日题目已安排稍后' : '今天暂无到期题目';
  return <section className="review-plan-page scroll-page" aria-label="复习计划" aria-busy={loading} data-snapshot-version={snapshot?.snapshotVersion}>
    <header className="review-plan-heading"><div><h2>复习计划</h2><p>{today ? `${today} · 学习时区 ${zone}` : api ? '正在读取当前学习日…' : '请在桌面应用中管理复习。'}</p></div><div className="review-heading-actions"><button className="button" disabled={!api || !!busy || frozen} onClick={() => setAddOpen(true)}><Icon name="library" />添加题目</button><button className="button" aria-expanded={budgetOpen} disabled={!summary || !!busy || frozen} onClick={() => { setBudget(summary?.budget === null ? '' : String(summary?.budget ?? 3)); setBudgetOpen(!budgetOpen); }}>复习量设置</button></div></header>
    {budgetOpen && <form className="review-budget-form" onSubmit={event => { event.preventDefault(); if (!api) return; const value = budget.trim() ? Number(budget) : null; if (value !== null && (!Number.isInteger(value) || value < 1 || value > 1000)) { setFailure('每日复习量请填写 1–1000 的整数，或留空表示不限量。'); return; } void action('budget', async () => { await api.saveLearningSettings({ dailyReviewBudget: value }); await changed(); setBudgetOpen(false); setMessage('每日复习量已更新。'); }); }}><div className="review-budget-field"><span><label htmlFor={budgetInputId}>每日复习量</label><HelpHint label="每日复习量说明">控制每天推荐的复习题数，不改变到期日；与新题练习目标分开。留空不限量。</HelpHint></span><input id={budgetInputId} type="number" min={1} max={1000} value={budget} disabled={!!busy || frozen} placeholder="留空不限量" onChange={event => setBudget(event.target.value)} /></div><button className="button" disabled={!!busy || frozen}>保存</button><button type="button" className="text-button" disabled={!!busy} onClick={() => setBudgetOpen(false)}>取消</button></form>}
    <section className="review-action-card" aria-label="今日复习行动"><div className="review-action-main"><p className="review-eyebrow">今日推荐</p><h3>{actionTitle}</h3>{summary && <p>已复习 {summary.reviewedToday} 题 · {summary.budget === null ? '不限量' : `每日量 ${summary.budget} 题`}{summary.extraDueCount > 0 && <> · 另有 {summary.extraDueCount} 题到期</>}</p>}{summary && summary.budget !== null && <div className="review-progress" role="progressbar" aria-label="今日复习进度" aria-valuemin={0} aria-valuemax={budgetNumber ?? Math.max(1, summary?.reviewedToday ?? 1)} aria-valuenow={budgetNumber ? Math.min(summary?.reviewedToday ?? 0, budgetNumber) : summary?.reviewedToday ?? 0} aria-valuetext={summary ? `已复习 ${summary.reviewedToday} 题，${summary.budget === null ? '不限量' : `每日量 ${summary.budget} 题`}` : '正在读取'}><span style={{ transform: `scaleX(${summary?.budget === null ? summary.reviewedToday > 0 ? 1 : 0 : ratio})` }} /></div>}</div><div className="review-action-side"><button className="button primary" disabled={!canBegin || !!busy || loading || frozen} onClick={() => { void begin(); }}>{busy === 'session' ? '正在准备…' : session ? '继续本轮复习' : '开始今日复习'}<span aria-hidden="true">→</span></button>{summary && <div className="review-quiet-links">{summary.extraDueCount > 0 && <button className="text-button" onClick={() => filter({ view: 'all', status: 'due', date: undefined })}>查看全部到期 {summary.dueCount} 题</button>}{summary.pendingAssessmentCount > 0 && <button className="text-button" onClick={() => filter({ view: 'all', status: 'pending', date: undefined })}>待补自评 {summary.pendingAssessmentCount} 题</button>}{summary.unassessedCount > 0 && <button className="text-button" onClick={() => filter({ view: 'all', status: 'unassessed', date: undefined })}>待首次评估 {summary.unassessedCount} 题</button>}</div>}</div></section>
    {failure && <div className="review-error-panel" role="alert"><p>未能完成操作：{failure}</p><button className="button" disabled={!!busy} onClick={() => { void load(); }}>重试读取</button></div>}{message && <p className="review-message" role="status">{message}</p>}
    <nav className="review-view-tabs" aria-label="复习视图">{([{ id: 'today', label: '今日复习' }, { id: 'all', label: '全部题目' }, { id: 'calendar', label: '日历' }] as const).map(tab => <button key={tab.id} aria-pressed={view === tab.id} onClick={() => filter({ view: tab.id, date: tab.id === 'calendar' ? today : undefined, status: undefined })}>{tab.label}</button>)}</nav>
    <div className={`review-content-grid ${detailId ? 'has-detail' : ''}`}>
      <section className="review-list-panel" aria-label="复习题目列表"><div className="review-panel-heading"><div><h3 ref={listHeading} tabIndex={-1}>{view === 'today' ? '今日推荐题目' : query.date ? `${query.date} 的安排` : '全部复习题目'}</h3><p>{loading ? '正在读取题目…' : `${rows.total} 题${query.status ? ` · ${statusLabels[query.status]}` : ''}`}</p></div>{query.date && <button className="text-button" onClick={() => filter({ date: undefined, view: 'all' })}>清除日期</button>}</div>
        <div className="review-filters"><label className="review-search">搜索题目<input type="search" value={search} placeholder="输入题名" onChange={event => setSearch(event.target.value)} /></label><details className="review-advanced-filters" open={filtersOpen} onToggle={event => setFiltersOpen(event.currentTarget.open)}><summary>更多筛选{query.listId || query.tag || query.status || query.sort === 'recent' ? ' · 已筛选' : ''}</summary><div><label>题单<select value={query.listId ?? ''} onChange={event => filter({ listId: event.target.value || undefined })}><option value="">全部题单</option>{snapshot?.listOptions.map(option => <option value={option.id} key={option.id}>{option.title}</option>)}</select></label><label>主题<select value={query.tag ?? ''} onChange={event => filter({ tag: event.target.value || undefined })}><option value="">全部主题</option>{snapshot?.tagOptions.map(tag => <option key={tag}>{tag}</option>)}</select></label><label>状态<select value={query.status ?? ''} onChange={event => filter({ status: event.target.value as ProblemReviewStatus || undefined, view: 'all' })}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>排序<select value={query.sort ?? 'due'} onChange={event => filter({ sort: event.target.value as 'due' | 'recent' })}><option value="due">下一次安排</option><option value="recent">最近复习</option></select></label></div></details></div>
        <div className="review-select-toolbar"><label><input type="checkbox" aria-label="全选本页题目" disabled={!rows.items.length || loading || !!busy || frozen} checked={rows.items.length > 0 && rows.items.every(row => selection.has(row.problemId))} onChange={event => selectPage(event.target.checked)} />全选本页</label>{selection.size > 0 && <><span>已选 {selection.size} 题</span><button className="text-button" onClick={() => setSelection(new Map())}>清除选择</button></>}</div>
        {selection.size > 0 && <div className="review-batch-toolbar" aria-label="已选题目批量操作"><button className="button" disabled={!!busy || frozen} onClick={() => { void begin([...selection.keys()]); }}>复习所选 {selection.size} 题</button><button className="button" disabled={!!busy || frozen} aria-expanded={deferOpen} onClick={() => { setDeferDate(today ? addDays(today, 1) : ''); setDeferOpen(!deferOpen); }}>延期 {selection.size} 题</button><button className="button" disabled={!!busy || frozen} onClick={() => { void batch({ scheduledAt: null }, 'defer-clear'); }}>取消延期</button><button className="button" disabled={!!busy || frozen} onClick={() => { void batch({ suspended: true }, 'pause'); }}>暂停 {selection.size} 题</button><button className="button" disabled={!!busy || frozen} onClick={() => { void batch({ suspended: false }, 'resume'); }}>恢复 {selection.size} 题</button></div>}
        {deferOpen && selection.size > 0 && <form className="review-defer-form" onSubmit={event => { event.preventDefault(); if (!deferDate || !today || deferDate < today) { setFailure('请选择今天或之后的明确延期日期。'); return; } void batch({ scheduledAt: archiveDateBoundary(deferDate, zone) }, 'defer'); }}><label>延期到（{zone}）<input type="date" min={today} value={deferDate} disabled={!!busy || frozen} onChange={event => setDeferDate(event.target.value)} /></label><button className="text-button" type="button" disabled={!!busy || frozen} onClick={() => setDeferDate(today ? addDays(today, 1) : '')}>明天</button><button className="text-button" type="button" disabled={!!busy || frozen} onClick={() => setDeferDate(today ? addDays(today, 7) : '')}>一周后</button><button className="button" disabled={!!busy || frozen}>确认延期 {selection.size} 题</button></form>}
        <div className="review-table-heading" aria-hidden="true"><span>题目 / 主题</span><span>最近自评</span><span>下一次安排 / 状态</span></div><ul className="review-plan-list">{rows.items.map(row => <li className="review-plan-row" key={row.problemId} data-selected={detailId === row.problemId}><input aria-label={`选择 ${row.title}`} type="checkbox" checked={selection.has(row.problemId)} disabled={!!busy || frozen || loading} onChange={event => { const checked = event.currentTarget.checked; setSelection(previous => { const next = new Map(previous); if (checked) next.set(row.problemId, row.revision); else next.delete(row.problemId); return next; }); }} /><div className="review-row-subject"><button ref={node => { if (node) rowButtons.current.set(row.problemId, node); else rowButtons.current.delete(row.problemId); }} className="review-row-title" aria-expanded={detailId === row.problemId} onClick={event => openDetail(row, event.currentTarget)}>{row.title}</button><p>{difficultyLabel(row.difficulty)} · {row.tags.join('、') || '暂无主题'}</p></div><div className="review-row-rating"><strong>{ratingLabel(row.latestRating)}</strong><span>最近复习 {instantLabel(row.lastReviewedAt, zone)}</span></div><div className="review-row-schedule"><strong>{row.card ? instantLabel(row.effectiveDueAt, zone) : '评估后安排'}</strong><div className="review-statuses">{row.statuses.map(status => <span key={status} data-status={status}>{statusLabels[status]}</span>)}{row.scheduledAt && <span>手动延期</span>}</div></div><button className="text-button review-row-open" aria-label={`查看 ${row.title} 详情`} onClick={event => openDetail(row, event.currentTarget)}>详情 <span aria-hidden="true">→</span></button></li>)}</ul>
        {!rows.items.length && !failure && <div className="review-empty"><h4>{loading ? '正在读取复习…' : !summary?.totalCount ? '还没有复习题目' : search || query.status || query.listId || query.tag || query.date ? '当前筛选没有题目' : view === 'today' ? '今天暂无推荐复习' : '还没有题目'}</h4>{!loading && <><p>{!summary?.totalCount ? '添加题目，首次自评后安排复习。' : view === 'today' ? '可查看待评估、待补评或全部题目。' : '清除筛选，或选择其他日期。'}</p><button className="text-button" disabled={!api} onClick={() => !summary?.totalCount ? setAddOpen(true) : (setSearch(''), filter({ view: 'all', status: undefined, date: undefined, listId: undefined, tag: undefined }))}>{!summary?.totalCount ? '添加题目' : '查看全部题目'}</button></>}</div>}
        <PageNumbers page={rows} busy={loading || !!busy} onPage={offset => setQuery(previous => ({ ...previous, offset }))} />
      </section>
      {detailId ? <aside className="review-detail-panel" aria-label="题目复习详情" aria-busy={detailLoading}><div className="review-panel-heading"><div><h3 ref={detailHeading} tabIndex={-1}>{detail?.item.title ?? '正在读取…'}</h3></div><button className="review-close" aria-label="关闭题目详情" onClick={closeDetail}>×</button></div>{detailFailure && <div className="review-error" role="alert"><p>{detailFailure}</p><button className="text-button" onClick={() => { void loadDetail(); }}>重试读取详情</button></div>}{detail && <>
        <dl className="review-detail-facts"><div><dt>下一次安排</dt><dd>{detail.plan.card ? instantLabel(detail.item.effectiveDueAt, zone) : '待首次评估'}</dd></div><div><dt>最近自评</dt><dd>{ratingLabel(detail.plan.latestRating)}</dd></div><div><dt>计划状态</dt><dd>{detail.item.statuses.map(status => statusLabels[status]).join(' · ')}</dd></div></dl><div className="review-detail-actions"><button className="button" disabled={!!busy || frozen || detail.plan.suspended || !detail.plan.card} onClick={() => { void begin([detailId], detailPracticeSource ?? makeReviewPracticeSource(snapshot?.query ?? query)); }}>开始复习这题</button><button className="button" disabled={!!busy || frozen} onClick={() => setRecallOpen(!recallOpen)} aria-expanded={recallOpen}>回忆思路</button><button className="button" disabled={!!busy || frozen} onClick={() => setRatingMode({ kind: 'manual' })}>记录今天的复习</button></div>{!detail.plan.card && <p className="review-help">先记录首次自评，再开始复习。</p>}{recallOpen && <section className="review-recall"><h4>独立回忆</h4><p>试着解释算法、复杂度和边界情况，再记录自评。</p><button className="text-button" onClick={() => setRatingMode({ kind: 'manual' })}>记录回忆自评 →</button></section>}
        {opportunities.total > 0 && <section className="review-pending-assessments"><h4>待补自评</h4>{opportunities.items.map(opportunity => <div key={opportunity.id}><p><strong>{opportunity.learningDate} · 官方 AC</strong><span>确认于 {instantLabel(opportunity.acceptedAt, opportunity.timeZone)}（{opportunity.timeZone}）</span>{opportunity.sourceDeleted && <span className="review-warning">来源档案已删除，无法查看代码；官方通过记录已保留。</span>}</p><button className="text-button" disabled={!!busy || frozen} onClick={() => setRatingMode({ kind: 'official', opportunity })}>补填这次自评</button></div>)}<PageNumbers page={opportunities} busy={opportunityLoading} onPage={setOpportunityOffset} /><p className="review-help">记不清时可跳过，记录今天的复习。</p></section>}
        <section className="review-evidence-links"><h4>笔记与练习档案</h4><div><button className="text-button" disabled={!!busy || frozen} onClick={() => { if (onNotes) onNotes(detailId); else void loadNotes(); }}>{notes ? '刷新本题笔记' : '查看本题笔记'}</button>{onArchives && <button className="text-button" onClick={() => onArchives(detailId)}>查看练习档案</button>}</div>{notes && <ul>{notes.map(note => <li key={note.id}><button className="text-button" disabled={!!busy || frozen} onClick={() => { void action('note', async () => { const value = await api?.note(note.id); if (!value || value.subjectId !== detailId) throw new Error('这篇笔记已经不存在或不属于当前题目。'); setOpenedNote(value); }); }}>{note.current.title}</button> <span>· {note.current.state === 'draft' ? '草稿' : '已确认'}</span></li>)}{!notes.length && <li>本题暂无笔记。</li>}</ul>}{openedNote && <div className="review-note-preview"><div className="review-panel-heading"><h4>{openedNote.current.title}</h4><button className="text-button" onClick={() => setOpenedNote(null)}>收起笔记</button></div><Markdown text={openedNote.current.markdown} onOpenLink={url => { void api?.openWebLink(url).catch(error => callbacks.current.onError(errorText(error))); }} onAttachment={hash => { void api?.exportAttachment(hash).catch(error => callbacks.current.onError(errorText(error))); }} /></div>}</section>
        {detail.migration.itemIds.length > 0 && <details className="review-migration"><summary>旧计划合并记录 · {detail.migration.itemIds.length} 个</summary><p>合并策略：{detail.migration.strategy} · 历史评分 {detail.migration.historicalObservations} 条。</p>{detail.migration.conflict && <p className="review-warning">旧暂停或延期有冲突，已按保守合并策略处理；可在管理列表调整。</p>}<p className="review-help">旧卡：{detail.migration.itemIds.join('、')} · 时区 {zone}</p>{detail.legacyPlans?.map(plan => <details className="review-legacy-plan" key={plan.id}><summary>{legacyTargetLabel(plan.target)} · {legacyLanguageLabel(plan.language)} 的旧计划快照</summary><p>旧到期 {instantLabel(plan.dueAt, zone)} · {plan.suspended ? '已暂停' : '未暂停'} · {plan.scheduledAt ? `延期到 ${instantLabel(plan.scheduledAt, zone)}` : '无手动延期'}</p><p className="review-help">旧卡 {plan.id} · 算法 {plan.algorithmVersion}</p><pre className="review-legacy-snapshot">{JSON.stringify({ initialCard: plan.initialCard, card: plan.card, parameters: plan.parameters, createdAt: plan.createdAt, updatedAt: plan.updatedAt }, null, 2)}</pre></details>)}{detail.legacySources && <><h4>旧来源评分与更正</h4>{detail.legacySources.items.map(source => <article className="review-history-event" key={source.eventId}><div><time>{instantLabel(source.observedAt, zone)}</time><strong>{source.kind === 'correction' ? '更正为 ' : ''}{ratingLabel(source.rating)}</strong><span>{legacyTargetLabel(source.target)} · {legacyLanguageLabel(source.language)}</span></div><p>旧卡 {source.itemId}<br />原事件 {source.eventId}{source.correctsEventId && <><br />更正来源 {source.correctsEventId}</>}<br />记录于 {instantLabel(source.createdAt, zone)} · 算法 {source.algorithmVersion}</p></article>)}{!detail.legacySources.total && <p className="review-help">没有旧来源评分。</p>}<PageNumbers page={detail.legacySources} busy={detailLoading} onPage={setHistoryOffset} /></>}</details>}
        <section className="review-history"><div className="review-panel-heading"><h4>评分时间线</h4></div>{detail.events.items.map(event => <article className="review-history-event" key={event.id}><div><time>{event.learningDate}</time><strong>{event.kind === 'correction' ? `更正为 ${ratingLabel(event.rating)}` : ratingLabel(event.effectiveRating)}</strong><span>{sourceLabels[event.source]}{event.isInitialAssessment ? ' · 首次评估' : event.source === 'legacy' ? ' · 历史复习' : event.kind === 'review' ? ' · 复习' : ''}</span></div><p>记录于 {instantLabel(event.observedAt, event.timeZone)} · {event.timeZone}{event.kind === 'review' && event.rating !== event.effectiveRating && <> · 原评分 {ratingLabel(event.rating)}</>}{event.sourceDeleted && ' · 来源档案已删除'}{event.legacySourceEventIds.length > 1 && <> · 合并 {event.legacySourceEventIds.length} 条旧卡评分</>}</p>{event.kind === 'review' && <button className="text-button" disabled={!!busy || frozen} onClick={() => setRatingMode({ kind: 'correction', event })}>修改这次自评</button>}</article>)}{!detail.events.total && <p className="review-help">暂无评分。</p>}<PageNumbers page={detail.events} busy={detailLoading} onPage={setHistoryOffset} /></section>
        {latestEvents.length > 0 && <section className="review-rating-distribution" aria-label="本页自评记录分布"><h4>本页自评记录 · {latestEvents.length} 条</h4>{counts.map(row => <div key={row.value}><span>{row.title}</span><div className="review-distribution-track"><i style={{ transform: `scaleX(${row.count / latestEvents.length})` }} /></div><strong>{row.count}</strong></div>)}</section>}
      </>}</aside> : <aside className="review-chart-panel" aria-label="复习负担图表">
        <section className="review-seven-days"><div className="review-panel-heading"><div><h3>未来七天</h3><p>预计复习安排</p></div></div>{snapshot ? <><div className="review-bars" aria-label="每天预计复习题数">{snapshot.next7.map(day => { const max = Math.max(1, ...snapshot.next7.map(row => row.scheduledCount)); const label = `${day.date}，预计安排 ${day.scheduledCount} 题${day.overdueCount ? `，逾期 ${day.overdueCount} 题` : ''}`; return <button key={day.date} className="review-bar-button" aria-pressed={query.date === day.date} aria-label={label} title={label} onClick={() => selectDate(day.date)}><strong>{day.scheduledCount}</strong><span className="review-bar-rail"><i style={{ '--bar-scale': day.scheduledCount / max } as CSSProperties} /></span><span>{day.date === today ? '今天' : dateLabel(day.date)}</span></button>; })}</div><details className="review-chart-values"><summary>查看数值</summary><ul>{snapshot.next7.map(day => <li key={day.date}><button className="text-button" onClick={() => selectDate(day.date)}>{day.date}：安排 {day.scheduledCount} 题{day.overdueCount > 0 && `，逾期 ${day.overdueCount} 题`}</button></li>)}</ul></details></> : <div className="review-chart-placeholder">{failure ? '图表读取失败，请重试。' : '正在读取七天安排…'}</div>}</section>
        {view === 'calendar' && month && <section className="review-month-calendar" aria-label="月度复习日历"><div className="review-calendar-toolbar"><h3>{monthLabel(month)}</h3><div><button className="button" aria-label="上个月" onClick={() => filter({ month: shiftMonth(month, -1), date: `${shiftMonth(month, -1)}-01` })}>‹</button><button className="button" onClick={() => today && selectDate(today)}>今天</button><button className="button" aria-label="下个月" onClick={() => filter({ month: shiftMonth(month, 1), date: `${shiftMonth(month, 1)}-01` })}>›</button></div></div><div className="review-calendar-weekdays" aria-hidden="true">{['一', '二', '三', '四', '五', '六', '日'].map(day => <span key={day}>{day}</span>)}</div><div className="review-calendar-cells">{monthGrid(month).map(cell => { const day = dayMap.get(cell.date); return <button key={cell.date} disabled={!cell.inMonth || loading} aria-pressed={cell.date === query.date} aria-current={cell.date === today ? 'date' : undefined} aria-label={`${cell.date}，安排 ${day?.scheduledCount ?? 0} 题，已复习 ${day?.reviewedCount ?? 0} 题，首次评估 ${day?.firstAssessmentCount ?? 0} 题`} onClick={() => selectDate(cell.date)}><span>{Number(cell.date.slice(-2))}</span><small>{day?.scheduledCount ? `${day.scheduledCount} 题` : '—'}</small>{Boolean(day?.reviewedCount) && <em>已复习 {day?.reviewedCount}</em>}</button>; })}</div></section>}
        {summary && <section className="review-plan-summary"><h3>计划概况</h3><dl><div><dt>到期</dt><dd>{summary.dueCount} 题</dd></div><div><dt>逾期</dt><dd>{summary.overdueCount} 题</dd></div><div><dt>已暂停</dt><dd>{summary.suspendedCount} 题</dd></div><div><dt>手动延期</dt><dd>{summary.postponedCount} 题</dd></div><div><dt>今日稍后</dt><dd>{summary.deferredCount} 题</dd></div><div><dt>今日首次评估</dt><dd>{summary.firstAssessedToday} 题</dd></div></dl></section>}
      </aside>}
    </div>
    {addOpen && api && <AddReviewDialog api={api} onClose={() => setAddOpen(false)} onAdded={changed} onError={onError} />}
    {ratingMode && detail && <ProblemReviewRating key={`${ratingMode.kind}:${ratingMode.kind === 'official' ? ratingMode.opportunity.id : ratingMode.kind === 'correction' ? ratingMode.event.id : detailId}`} api={api} problem={{ id: detailId, title: detail.item.title }} mode={ratingMode} onSaved={changed} onDismiss={() => { setRatingMode(null); }} onError={onError} />}
  </section>;
}
